### ISSUE TITLE
Add Missing Documentation on TagQuery for UmbracoHelper

### ISSUE THREAD

**Issue by Attackmonkey** [umbraco/UmbracoDocs#1236]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/Documentation/Reference/Querying/UmbracoHelper/

## Describe the issue:
No documentation for the TagQuery property of the UmbracoHelper.

**Comment by Attackmonkey** [comment]
Pull request submitted: https://github.com/umbraco/UmbracoDocs/pull/1234

**Comment by dampee** [comment]
Hi @Attackmonkey 

Great to see some examples for the TagQuery. However, we try to minimize the method lists which are generated too from the [automatic TagQuery documentation](https://our.umbraco.com/apidocs/csharp/api/Umbraco.Web.TagQuery.html?q=tagquery).  

Could you update the PR a littlebit so that it feels more like an explanation with an example and not like the auto generated page?  

What do you think?

**Comment by dampee** [comment]
Just noticed that the PR is already merged by @marcemarc , but I think we can do better.  Do you have some time to help us out @Attackmonkey ?

**Comment by Attackmonkey** [comment]
Have you got an example in the docs that's more like what you're thinking of? I'll take a look and update the docs if so! Might take me a few days as I'm super busy this week, but happy to beef them up if need be :)

**Comment by sofietoft** [comment]
Hi! 
As we haven't seen any new activity on this issue in while, I'll close it for now.

If you feel it's still relevant, you're welcome to reopen it! 😁 
Thanks.

/Sofie
