### ISSUE TITLE
Add Next and Previous links to documentation

### ISSUE THREAD

**Issue by cosminiv** [umbraco/UmbracoDocs#1294]
Hi,

When reading the documentation it would be useful to have at the bottom of the page "Next" and "Previous" links. Otherwise I need to go back at the top of the page and track down the next page in the tree, which is tedious, especially on mobile.

Thanks

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Setup/index.md***

**Comment by jmayntzhusen** [comment]
Hey @cosminiv 

Thanks for the feedback. All tutorials that are on multiple pages already have these links though, and since all other articles are simply topics where there may not be a specific order to them I am not sure it would make sense. 

What we probably should do instead is to add some sort of Related Articles section at the bottom with suggestions on what else could be interesting to read, but we already have an issue up on that. https://github.com/umbraco/UmbracoDocs/issues/1072

Will close this for now based on the above 🙂
