### ISSUE TITLE
Custom Dashboard tutorial not working in v8 

### ISSUE THREAD

**Issue by rhealefever** [umbraco/UmbracoDocs#1539]
I'm going through the tutorials for v7 to see if they apply for v8, by following both tutorials side by side. The Custom Dashboard doesn't work in v8, and I'm pretty sure it must be because javascript is implemented differently in v8.

v7 working:
![image](https://user-images.githubusercontent.com/47108275/52398389-2c2d6680-2ab9-11e9-957c-d81518ca8117.png)

v8 not working:
![image](https://user-images.githubusercontent.com/47108275/52398402-38192880-2ab9-11e9-8fe9-dfb107a3a6ea.png)

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Tutorials/Creating-a-Custom-Dashboard/index.md***

**Comment by rhealefever** [comment]
A similar thing happens while following [Creating a property editor](https://our.umbraco.com/documentation/Tutorials/Creating-a-Property-Editor/).
v7: 
![image](https://user-images.githubusercontent.com/47108275/52402144-cc888880-2ac3-11e9-895c-871e5513441a.png)
![image](https://user-images.githubusercontent.com/47108275/52402151-d01c0f80-2ac3-11e9-9e8f-dab34e4895e7.png)

v8:
![image](https://user-images.githubusercontent.com/47108275/52402159-d611f080-2ac3-11e9-893d-29cfae11360a.png)
![image](https://user-images.githubusercontent.com/47108275/52402166-db6f3b00-2ac3-11e9-9d57-2307c823b403.png)

Everything works fine until Javascript is involved. The custom property editor doesn't show up at all.
v7:
![image](https://user-images.githubusercontent.com/47108275/52402202-f5108280-2ac3-11e9-8ef4-72d373c8ea48.png)

v8:
![image](https://user-images.githubusercontent.com/47108275/52402205-f80b7300-2ac3-11e9-945a-1710ecc6d35f.png)

**Comment by marcemarc** [comment]
@rhealefever Are there any console errors? these may point to which bit isn't working!

**Comment by jmayntzhusen** [comment]
Closing this as this was done on a pre-release version, there are probably still some things that need to be updated, but will need more specific information for that 🙂

**Comment by robgoddes** [comment]
Hello jmayntzhusen,

Is there any reason why this issue is closed? Was it replaced with a correctly working tutorial?

I’m following the **Creating a Custom Dashboard Tutorial** and I have the same issue... the dashboard doesn't appear:
https://github.com/readingdancer/UmbracoDocs/blob/v8-edits/Tutorials/Creating-a-Custom-Dashboard/index.md

Regards,
Robert

**Comment by jmayntzhusen** [comment]
Hey @robgoddes 

This issue was reported during some alpha testing of v8 before the initial release - because we heard no response of the tester we ended up closing it. The turotial is not yet updated to v8, it will only work on v7 for now, but if you run into this exact same issue on a current release of v8 then we can reopen the issue 🙂

**Comment by robgoddes** [comment]
Thanks for the response @jmayntzhusen,

You are correct, the tutorial does not work on v8.1.0

The tutorial describes that the "**dashboard.config**" file must be added to the "**/config**" folder but this doesn't work.

However, I did manage to get the dashboard appearing by adding the following code into the **package.manifest** file, at location: ~\App_Plugins\StarterKit\package.manifest

`"dashboards":[
    {
        "alias": "customWelcomeDashboard",
        "view": "/App_Plugins/CustomWelcomeDashboard/WelcomeDashboard.html",
        "sections": [ "content" ],
        "weight": -10
    }
]`

The only issue is that the dashboard tab name appears with square brackets around it, e.g. **[customWelcomeDashboard]**. The tab name is being taken from the "alias".

It's not very elegant and I can't seem to find a way to remove the brackets. See image below...

<img width="327" alt="Screen Shot 2019-07-25 at 8 33 30 am" src="https://user-images.githubusercontent.com/24960/61833266-153bce80-aeb7-11e9-8a9d-d50566c65552.png">

Surely, there must be some way to remove the [ ] in tab name?

**Comment by robgoddes** [comment]
Thanks @jmayntzhusen,

You are correct, the tutorial doesn't work in v8.1.0, because placing the **dashboard.config** file in the **/config** folder doesn't work.

Instead, I placed the following code in the '**package.manifest**' file in the **app_plugins** folder and it worked:

`"dashboards":  [
        {
            "alias": "myCustomDashboard",
            "view":  "/App_Plugins/myCustom/dashboard.html",
            "sections":  [ "content", "settings" ],
            "weight": -10
        }
    ]`

The docs on the following URL showed how to do it correctly:
https://our.umbraco.com/documentation/Extending/Dashboards/#registering-your-own-dashboard

I also needed to add a language key, so the tab name appeared without brackets:
https://our.umbraco.com/documentation/Extending/Dashboards/#add-language-keys

So, I guess you can close this ticket but it may be wise to add a note on the tutorial to point to the fix for v8 users?

Thanks again,
Robert

**Comment by sofietoft** [comment]
Hi @robgoddes and @rhealefever !

Apologies for the wait!
@jmayntzhusen has been working on getting the Dashboard tutorial updated. 
He has a WIP PR: https://github.com/umbraco/UmbracoDocs/pull/1642
I'm sure he'd love your input there, as it sounds like you managed to work this out!

**Comment by jmayntzhusen** [comment]
The tutorial is now up to date as per https://github.com/umbraco/UmbracoDocs/pull/1984

Please report any issues you may find in a new issue.
