### ISSUE TITLE
Conflicting advice on gitignore

### ISSUE THREAD

**Issue by TheBeardedLlama** [umbraco/UmbracoDocs#1541]
Hey guys/gals,
I'm slightly confused by the advice given with regards to gitignore.
The docs say ignore everything under the `Umbraco` directory, but the gitignore says that we need to have `umbraco/developer/packages` in source.
Could you please clarify? 
I've been seeing this for a while, but only just thought to ask the question.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Getting-Started/Code/Source-Control/index.md***

**Comment by TheBeardedLlama** [comment]
same goes for the `app_data/packages` folder which is included in its entirety according to the gitignore

**Comment by nul800sebastiaan** [comment]
No conflicts there, you can exclude folders from the ignore file. Both are excluded from the example ignore file linked to from the documentation on these two lines:

https://github.com/github/gitignore/blob/master/Umbraco.gitignore#L19-L20

**Comment by TheBeardedLlama** [comment]
I'm sorry @nul800sebastiaan but that wasn't very friendly or helpful.
You haven't quite dealt with the question at hand.

The link you provided is what I was referring to and they are not being excluded; they are being *included*, hence my request for clarification.

**Comment by marcemarc** [comment]
@TheBeardedLlama it depends on Umbraco version, in the V4/V6 days, some packages would install inside the /Umbraco folder, and also have corresponding files in app_data - so it was important then to exclude the entire Umbraco folder from source control - but include the package files! -  but since V7 there is now a separate app_plugins folder where packages should install themselves, so there is no longer a need to include the two folders you mention in source control - but I imagine the gitignore file has been handed down through generations and still has the two references in and there has been no imperative to remove them!

**Comment by TheBeardedLlama** [comment]
That was much better! Thank you for taking the time to explain @marcemarc 
In this case, should there be a note in the docs and/or the gitignore to indicate the above?
If that's the case, I'll submit the relevant PR's

**Comment by marcemarc** [comment]
@TheBeardedLlama yep, I'm not super-sure how the gitignore is maintained - but feels like a note above the two lines explaining the version specific ignorance. I guess it's not doing any harm allowing those folders in V7 as nothing should be stored in them, but can cause confusion to see them there and not know why!

**Comment by dampee** [comment]
If you exclude the Umbraco folder, you will run into trouble on cloud as you need to check in everything.  I guess, if we are adding version specific information, you might verify that there is at least a reference to https://our.umbraco.com/Documentation/Getting-Started/Code/Source-Control/

**Comment by TheBeardedLlama** [comment]
cheers @marcemarc 
yeah that's what I was thinking
gitignore is maintained by github, so I will submit a PR over there

sorry @dampee , but I'm not sure I understand what you mean
are you saying that the entire Umbraco folder needs to be committed to source? that doesn't sound right to me

**Comment by dampee** [comment]
@TheBeardedLlama 
Actually, not only Umbraco, but also Umbraco_Client and the Bin folder.  The git repo on cloud is the website you are running. 
Anyway, if you do a PR, I'll verify if we need to mention something about cloud.

Looking forward to your PR.  Do you refer to this Issue?  (can be done with a hash like so: #1541)

**Comment by TheBeardedLlama** [comment]
@dampee ah, are you referring to the Umbraco Cloud product? as opposed to running in the cloud, e.g. Azure?

**Comment by nul800sebastiaan** [comment]
@TheBeardedLlama Sorry, yes, instead of excluded I mean included, silly brain of mine! 

Apologies if I didn't sound friendly, I will let you know I was in a good mood while I gave you a link and some background info on how you can implement the recommendation in the docs. 

Good to see you got some more details! 👍

**Comment by nul800sebastiaan** [comment]
@dampee Please note that on Umbraco Cloud we ship with a pre-configured `.gitignore` file which of course includes the Umbraco folder. The example ignore file linked should be used for fresh stand-alone projects.
