### ISSUE TITLE
V8 Rich Text Editor not working as parameter in macro

### ISSUE THREAD

**Issue by trollsudd** [umbraco/UmbracoDocs#1750]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about? 
https://our.umbraco.com/forum/templates-partial-views-and-macros/82089-tinymce-as-macro-parameter

## Describe the issue:
I tried to follow a guide (v7) for adding a RTE in macro:
https://our.umbraco.com/forum/templates-partial-views-and-macros/82089-tinymce-as-macro-parameter

When I try to create an instance of this macro I get a 404 error: 

"Request error: The URL returned a 404(not found)"
The gui seems to look for : localhost/umbraco/rte

I have checked with Umbraco support:
"Unfortunately, we do not have any documentation on that for v8 and doesn't look like this has been tested yet."

**Comment by nul800sebastiaan** [comment]
Thanks, make sure to discuss this further in the forum post you linked to. The situation has changed a bit for v8 and it's likely you'll need to update a bit more of your custom code.

I'll close this issue since it's not a macro parameter editor we bundle with Umbraco by default, it requires some custom code.
