### ISSUE TITLE
Incomplete Caching Documentation

### ISSUE THREAD

**Issue by hidarikani** [umbraco/UmbracoDocs#2149]
## What type of issue is it?
Incomplete documentation

## What article/section is this about?
https://our.umbraco.com/Documentation/Reference/Cache/

## Describe the issue
The caching documentation is incomplete because it only covers advanced use cases. Info from this [thread](https://our.umbraco.com/forum/developers/api-questions/65040-Using-ICacheRefresher-to-clear-cache) should be added to the docs. Quote from the thread:

> If you just want to clear your own cache based on publishing then you don't even need to have your own ICacheRefresher. You can use an event.

Also, I wonder why Umbraco docs don't mention [output caching](https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/controllers-and-routing/improving-performance-with-output-caching-cs). Does that mean that Umbraco enables output caching by default?

**Comment by sofietoft** [comment]
Thanks for reporting this @hidarikani !

Just to clarify - are you using Umbraco 7 or 8?
The forum thread you're linking to is from 2015, so I'm assuming it's Umbraco 7?

In that case, we do have a but more extensive and details docs on caching for that version: https://our.umbraco.com/Documentation/Reference/Cache/index-v7 

It agree that we still need more documentation on caching for Umbraco 8! 
Perhaps you would be up for writing some? 😎 

Regarding your question about output caching - will need to run that by some of our experts in order to give you an answer on that!

**Comment by hidarikani** [comment]
I'm using 7 at the moment but I think my comment applies both for 7 and 8. I don't feel like I have enough knowledge to contribute yet.

**Comment by sofietoft** [comment]
Ah, sure thing! 😄 
For Umbraco 8, this issue has already been created: #1874 

Is there any specific information you feel is missing, or is it just the entire section about Caching in general?

**Comment by sofietoft** [comment]
Had a chat with some experts on this topic, and we found this: https://our.umbraco.com/Documentation/Reference/Templating/Mvc/partial-views#caching 

Perhaps this could be what you're looking for? 😄

**Comment by sofietoft** [comment]
Hi @hidarikani - It's been a while since I've heard from you here.

Did you manage to find the information you were looking for? 😄

**Comment by sofietoft** [comment]
Hi @hidarikani !

It's been a while since I've seen any activity on this one.
I hope that means you found the information you needed to complete your work 💪 

I'll close this one for now, as we already have [an issue mentioning the fact that the Caching docs needs to be updated](https://github.com/umbraco/UmbracoDocs/issues/1874).

Thanks again for reporting! 😄
