### ISSUE TITLE
Blacklisted and Excluded

### ISSUE THREAD

**Issue by webdivauk** [umbraco/UmbracoDocs#2484]
I'd like to suggest that the term 'Blacklisted' in the first image be changed to 'Excluded'. As someone very new to coding with Umbraco and having to follow every letter of the tutorial I found myself having to go back to the start of the document to confirm to myself that the 'Blacklisted' and 'Excluded' was one and the same.,  

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Tutorials/Creating-an-XML-Site-Map/index.md***

**Comment by sofietoft** [comment]
Thanks for pointing this out @webdivauk ! 💪 

Just so I'm 100% sure I understand what you're saying here:
The field for the list is called "Excluded Document Type" in both text and code snippets - but in the screen dumps of the backoffice, the actual name of the field is Blacklisted Document Types.

Have I understood that correctly?

**Comment by webdivauk** [comment]
Hi 

That’s right. 👍

**Comment by sofietoft** [comment]
Great! Thanks for confirming @webdivauk .

I believe it was @marcemarc who wrote this article? Perhaps he can shed some light on this 😁

**Comment by marcemarc** [comment]
Yes, I think in the original tutorial we were using the term 'blacklisted' but that term doesn't necessarily make universal sense in this context... and so it was updated to be excluded to be clearer... but I bet we forgot to update the screen grabs... @webdivauk  have you just followed the tutorial? and might happen to have views of the steps with the matching property name easily to hand?? and could take some new screenshots? if so that would be ace
