### ISSUE TITLE
Version Clarification

### ISSUE THREAD

**Issue by codeguise** [umbraco/UmbracoDocs#2586]
When attempting to get documentation for version 8 caching using google search this page appears in the results. It is still valid for version 7 but I was very confused why it wasn't working for version 8. This page needs a message that it is for version 7 only. Version 8 needs much more, clearer, documentation on this subject.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Reference/Cache/updating-cache.md***

**Comment by sofietoft** [comment]
Hi @codeguise ! Thanks for the report.

We do have a bit about caching in Umbraco 8: https://our.umbraco.com/documentation/Reference/Cache/examples/tags
However, I realize it's not a lot! I'll make sure to poke some our experts, so we can get that ball rolling!

Regarding the version tagging on the Umbraco 7 article... when articles haven't been updated for Umbraco 8 they usually have a green box indicating that. However, in this case that article isn't an index.md, which is required for the box to show up 🙈 
We could add a statement at the top of the article instead, saying that the contents are only valid for Umbraco 7 - what do you think?

**Comment by sofietoft** [comment]
Apologies for the delay on this one @codeguise .

I've been through all the articles we have around caching - most of them not updated for Umbraco 8 yet, unfortunately.

Know that this is something we are looking into fixing!

For now, I've added a little warning to each of the Caching articles for Umbraco 7 (https://our.umbraco.com/Documentation/Reference/Cache/updating-cache).

As we already have [another issue listing the caching articles that still needs to be updated](https://github.com/umbraco/UmbracoDocs/issues/1874), I'll close this one for now.
Thanks again for raising the issue here. Much appreciated!
