### ISSUE TITLE
Information really light

### ISSUE THREAD

**Issue by thenexus00** [umbraco/UmbracoDocs#2625]
This page only really covers getting single form values and looping through form fields to output.

There are many forum posts out there in where people want to get basics such as the form name, GUID and so on. There are some solutions for Umbraco 7 such as:

var formStorage = new Umbraco.Forms.Data.Storage.FormStorage();
var form = formStorage.GetForm(Model.FormId);

Which do not work under Umbraco 8. It would be good to have some basic information on the doc on how to get form information such as name and GUID.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/Add-ons/UmbracoForms/Developer/Email-Templates/index.md***

**Comment by sofietoft** [comment]
Thanks for the report @thenexus00 ! 
We do have some more details on getting forms and record data in this article: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Working-With-Data/

What you're referring to here, is specific to the article on Email Templates - right?

**Comment by thenexus00** [comment]
Hi @sofietoft 
That does not seem to work in email templates though in Umbraco 8, only page stuff. This was even noted back in 7 by people in the forums and the work arounds they had do not work in 8 :(

**Comment by sofietoft** [comment]
Ah, I see. Thanks for helping me clarify this.

I'll run it by our Forms experts - they should be able to tell us how this is done in the latest versions.

**Comment by thenexus00** [comment]
I added to a post on the forums already. There are a couple of with people asking about version 8.
There was a git thread I read where things were supposedly added back in 2016 with people re-iterating in 2018 but other asking later saying it does not work and no one ever got back to those comments.

**Comment by sofietoft** [comment]
Sure seems that there's a high demand for this!

Looks like our Forms expert is currently on holiday. He'll be back next week though, and the task to look into this has been put on his desk 💪

**Comment by sofietoft** [comment]
Hi @thenexus00 !

We've had a couple of developers give this a look, and we have some more questions for you, in order to make sure we understand everything correctly.

You've been looking for more information on how to pull in the name and ID of the forms in the Email Templates.
This is already possible through `@inherits UmbracoViewPage<Umbraco.Forms.Core.Models.FormsHtmlModel>`. Our developers have tested the article you're referencing, and everything should be all set for Umbraco 8 as well.

Now, we're a bit confused as to what exactly it is, you're looking for here, that isn't already in the article.
Could you help us understand it a bit better?
Perhaps send us some links to these forum posts you mention, and if you have other references as well perhaps? 🤔

**Comment by thenexus00** [comment]
### Core issue
Umbraco forms have no means out of the box to have unique content per email. If you think client/site owner use they can build amazing looking forms after a dev has done the core work, setup workflow steps, set nice emails with templates and thank you pages but not the content of those emails.

### What I been doing/trying to do.

I want to be able to have a Document type with nodes sitting on the tree representing form content and for them to have a content picker a client can just select the form that the content belongs too.

Then in the email template fetching that content elements content and rendering it in the email.

At the moment I am doing this by a custom hidden field on the form that has the ID of the node for the content but this is not easy for a client to manage.

### Why I can not do it the way I want
- The form picker property outputs the GUID of the form
- I need to get the GUID of the form in the email template to be able to do a match
- In email templates I can not get the form name or GUID values out
- The workarounds for Umbraco 7 mentioned do not work in Umbraco 8

### The actual solution
The real solution is an update to Umrbaco forms itself

- Content editor component for each email form component. When you select email with or without template you should have a basic editor to be able to form content
- The editor needs a picker to select the field values created in the form so you can output those values.
- The ability to render that content in email view tempaltes

A client will want to create an autoresponder with template saying...

Dear John Smith,
Thank you for contacting us, your enquiry about [Value from dropdown] will be looked at by one of our team members and we will get back to you in 5 working days.

------------
Is this clearer?
- There is a feature lacking in Umbraco forms
- Trying to work around with a client manageable solution but roadblock with value output 
- Provided the ultimate solution.

LOTS of comments for a long time around the lack of being able to have custom email content per form with various work arounds people doing but I think my suggestion for ultimate update is straight forward but for now I just want the GUID of the form to use if possible.

**Comment by sofietoft** [comment]
Thanks a lot for all the additional details on this one @thenexus00 ! Much appreciated.

As you also mention yourself, it sounds more like a missing feature than missing documentation 🤔  Sure sounds like something that would be a neat feature!
I've had another chat with one of our Forms experts, and they agree.
Can I get you to add it to our Forms Issue tracker instead?
That should also put you in touch directly with our Forms experts when the issue is picked up.

**Comment by sofietoft** [comment]
Hi @thenexus00 !

Haven't heard back from you in a while, so I wanted to let you know, that I'll be closing this issue for now.
Please, if you haven't already, raise these questions and feature requests on the Umbraco Forms Issue tracker instead: https://github.com/umbraco/Umbraco.Forms.Issues/issues 

Then our Forms experts will take it from here 💪 
Thanks again for raising the issue!
