### ISSUE TITLE
Community Driven Umbraco Related Articles Section

### ISSUE THREAD

**Issue by marcemarc** [umbraco/UmbracoDocs#2659]
We've talked for quite a while about moving towards a flatter article driven format for the Umbraco Documentation - using tags to provide structure, but in order to make it easier for people to contribute from HQ devs or the community 'an article' on a particular part of Umbraco.

There are different types of documentation: guides, reference, tutorial etc and current structure of the docs although has improved over time - is still very organic and esoteric.

We've hoped the DocFX approach would lead us to this flatter article approach, or at least be a useful stepping stone, but it's now a couple of years later.

There appears to be a demand for trying to create a shared repository of articles/tips and ideas, that are related to working with Umbraco and perhaps .net generally.

Could we experiment now, by creating an Articles section with the existing Markdown files format - would people contribute articles here - would we attribute them etc - or perhaps this should be external to the official docs, but well signpointed from here and from within articles

What do we all think?

Would this experiment provide useful insight into the future restructuring plans of the docs? eg test the water a bit? if it generates more contribution? would it be difficult to review someone's article for the 'official docs'? eg what if somebody had a writing style where they wrote really really long sentences and rambled on (ummm me?) - would the VALE rules still apply here? Is there overlap with Skrift / 24 days in...

... didn't we have a place where we linked to, or displayed recent posts from 'community blogs'? ...  maybe making community blog article content amalgamated into a single search is another thought?

And most importantly what should such a section/knowledge base/community article thing be called?

**Comment by TimGeyssens** [comment]
Instead if trying to fit it all in one tool and having the extra hassle of maintaining the code responsible for the docs... why not use something like https://www.gitbook.com/ (the editor experience is great, you can just copy paste image, no need to clone a git repo in order to make a change...), can be all done web based... it's even free for open source...

**Comment by RachBreeze** [comment]
For me this section in the Umbraco  docs should be short examples of code.  It should not compete with Skrift or 24days in, but complement them.  An example might be "here's a tip for clearing down your cache on deployment"
`code snippet`
Here's an example powershell script for changing the client dependency version  in your TeamCity pipeline
Here's an example of how to change the client dependency version in Azure

**Comment by RachBreeze** [comment]
Sorry and in answer to where did it go, I saw it sitting in https://our.umbraco.com/documentation/
Under tips and tricks section 
And in the example above "Caching"

**Comment by marcemarc** [comment]
@RachBreeze I was thinking article on how to setup CDN with Umbraco - but is that more Skrifty? do you think? we're talking more quick nuggety tips and examples for everyday improvements? (or both?)

**Comment by TimGeyssens** [comment]
Why worry about competing with Skrift or 24days ? The more stuff there is floating around ... what would be valuable is a simple starting point that collects all of this and also matches it with the correct umbraco version...

**Comment by marcemarc** [comment]
Yep, I'm thinking amalgamating what's out there to make it discoverable might be more valuable next step? as people like to write their own stuff in their own style with attribution - but also keen to see if there was an 'official place' for this more ad-hoc supporting content - whether that would generate more sharing of knowledge - eg like yourself, starting blogging again - it can be a dilemma to decide where and how.

**Comment by RachBreeze** [comment]
When I originally wrote my thoughts it was for nuggets of information, categorised against each Umbraco version as mentioned.  
I like the structure of Microsoft docs https://docs.microsoft.com/en-us/ and was thinking there was a method for doing something similar with Umbraco, this doesn't replace other bloggers, but can act as a starting point.
If we are looking at another way of categorising articles and so on [Mike Taylor](https://twitter.com/m1ketayl0r) has explored something silmair with [uPractioners ](https://twitter.com/uPractitioners)

**Comment by marcemarc** [comment]
I'm wondering if we can get 5 example tips/nuggets/tricks together? perhaps in a google doc, just so it's immediately comprehensible the type of content we are discussing - and so we can get a feel for how each nugget might be structured, or different types of nuggets.. (as in my head it's valid to have a 'pointer' to a blog post or even forum post - a lot of useful information is out there but it's just not discoverable - this would be a way of discovering things...)

Title
Summary
Nugget
NuggetType
Nugget Content Tag?
UmbracoVersion

Google Doc here: https://docs.google.com/document/d/1Mn3CVRbx4TRwBq-4jg9OCmiPuGDi82BQrT5T9X5KLwA/edit?usp=sharing request access if you have something to add, let's see if we can get 5!

**Comment by nul800sebastiaan** [comment]
Just as a note the community blogs section is here: https://our.umbraco.com/community/blog-posts/ - anyone with an RSS feed can ask to be added in that section.

Work is on the way to split off the community section of Our into a new site where we have more control over the styling and content.

Other than that, I think it would be really cool to have curated comments on each docs article where people can leave tips in the form of "I did it this way". Although IMO it shouldn't be used for questions or discussion (hence the curated part).

Another thing to think about: the community Slack is a lively environment where people share problems and solutions all the time. I'm very sad that this is happening in a walled garden that Google can't search, how can we get those great answers out of there and into a crawlable format?

**Comment by TimGeyssens** [comment]
Sure rss is nice, but that requires you to setup a blog and that might not be worth the effort if you want to share something simple

Yeah non indexable stuff like slack (and even fb is used for asking tech questions) is not a good thing

**Comment by marcemarc** [comment]
Also linking for reference in this conversation Kev's DoStuffWithUmbraco
https://github.com/KevinJump/DoStuffWithUmbraco
that is another collection of examples and tips in small example led format

**Comment by miketaylorco** [comment]
Hi all - I realise that this thread is primarily related to developer content, but I'm wondering if there's any overlap here with my thinking on a community-driven Umbraco Practitioners website aimed at people in non-developer roles. The idea is to provide content value for people in non-dev roles, to engage them, and then to encourage them to contribute content on the site. I've struggled to find time for it lately, so it's stalled a little, but you can see the latest design thinking here: https://www.sketch.com/s/2f2a19dd-77c1-4fcc-b5a2-78acc4ae4e71

It feels like it might be better for all this stuff to be in one place, but I also think that non-devs might be a little intimidated by developer-heavy content, which is why I'd originally conceived it as a separate entity.

Anyway, not sure if this is useful or not in this context; let me know if there's anything in here that might be of value.

**Comment by marcemarc** [comment]
Thanks, @miketaylorco certainly worth mentioning in terms of a home/hub for community-created content - and your Sketch is very thought-provoking. There does feel like there is a gap for an article driven magazine-y digital offering for people who use Umbraco day to day - that keeps people up to date with new things in the world of Umbraco, and helps people get ideas of how to get more out of their Umbraco install, with a broad appeal for editors and implementors alike - straddling that grey area between editing content and installing plugins, tweaking configuration - looking out for 'numero Uno' if you pardon the pun... without going all developerish ...I think it would largely succeed or fail based on its content, but hard to plan and build something grand,  if not sure if it would take off? (and 2020 hasn't helped!!), - what's the smallest version of this that could be built and promoted? Could we write 5 example articles that might appeal to this audience? Create even an Uno site? (I'm sure Umbraco would support such an initiative), accompanied by an open appeal for writers, similar to how Skrift works, if it seemed to gain traction, then other ideas like in your sketch could evolve alongside the articles... T-shirts even! 

I think ultimately with these things we can try to wish there was one place that tied everything together, eg Our Umbraco - but this shouldn't get in the way of people writing and sharing interesting articles for the practitioner audience or any audience, successful things are easily subsumed into something else, whereas trying to work out everything first can hinder getting going... I'd be up for writing an article!

**Comment by miketaylorco** [comment]
Thanks @marcemarc - you're right, something like this would succeed or fail based on its content (and hence value), so I think the real trick here is to have the community *drive* it.

Yes, the site could (and should) contain articles etc. that are specifically written for publication on this site, but the real value of a site like this, I think, is that it could also be a kind of curated hub for content that already exists elsewhere, but this site just makes that stuff more discoverable for people. So, it should also be able to signpost people to existing Twitter threads, forum discussions on Our, blog posts, Skrift articles etc.

In order to do that, it has to be really **easy** for interested parties to submit content, and really obvious **how** they can do it. It doesn't even have to be their content, it could just be 'I've seen this thing that I thought was interesting to me, and it might help other people in this situation too.'

This also lowers the barrier to submission - you're not necessarily asking the community to generate new content, write articles, record videos etc. (although they could, and that would be great, but it's a fairly big ask) - you're potentially just asking them to fill in a URL and a couple of sentences, submit, job done.

You're also not diluting content or channels that already exist, you're just making that content more discoverable for people and directing them to it, as well as providing a vehicle for new content to be generated.

Because it's driven by community-generated content/submissions, it would be fairly challenging to moderate and manage those submissions, which was why I came up the concept of 'role ambassadors', where a small group of volunteers in specific roles would take a leading role (at least to start with) in terms of generating or locating/curating relevant content in that area, as well as moderating user-submitted content before it's published.

I think there's definitely potential in the idea, it's really just about finding the time and the technical assistance (my dev skills are somewhat out of date these days) to bring it to life. All help welcomed!

**Comment by marcemarc** [comment]
Ahh, so more of a community-curated content aggregator than a destination in its own right. The content exists for your target audience, but they can't find it. The community could help them find it. Would sending an email to someone be a really easy way for interested parties to submit content? The Role Ambassador would have the step of cutting and pasting and publishing the related info - I'm just thinking of a low tech way to start something to see if you are onto something as an experiment... and then see where it leads. If you created a trial Uno account on Umbraco Cloud, you could easily add an Umbraco Form for people to make submissions... be interesting to see how 'far off' that would be from what you would need to publish pages that provide categorisation and signposts to existing pieces - obviously still need to do T-shirts etc

**Comment by miketaylorco** [comment]
Yeah, or a mixture of the two. I like the 'destination in its own right' thing, but it's hard to continually generate the amount of useful content that would keep people coming back to it, so the 'community-curated content aggregator' aspect breathes some life into it without the need to constantly generate all-new content for the site when there's a ton of useful content around that might be hard for people to locate/discover.

I was thinking a simple Umbraco form for submitting curated content, which the role ambassadors would need to moderate somehow (Plumber, maybe? Eventually?). And for generating new content/articles, probably a 'let us know if you have an article you'd like to write/submit' function followed up by an email exchange.

I'll have a think about minimum viable solution; it sounds like a good approach to simplify to start with.

**Comment by marcemarc** [comment]
If you build it... they will Umbracome...

**Comment by miketaylorco** [comment]
Just need to find some dev help! 😊

**Comment by crgrieve** [comment]
Hello, 

I like the idea of aggregating all the useful info on Our. I know it's already in the RSS feed, but I think would be good if when searching in the Umbraco docs it could also search community posts (blogs, Skrift, 24 days, etc). This search would let folks find these "nuggets" you mention in this thread within the context of Our Umbraco.

We prototyped something like @miketaylorco  mentioned at the CG retreat a few years ago, allowing users to submit the content, linking to tweets aswell as blog posts, etc.

Thanks,
Carole

**Comment by sofietoft** [comment]
Hi all!
Thanks for pitching in on this idea here, about adding a community driven articles section to the Umbraco docs.

Since this discussion was initiated, Umbraco HQ has started a lot of new initiatives on the new Community website, and there's also a section where you can find and browse blog posts written by the community!
Therefore, I'll close this issue here for now.

Should you come across an article in the docs and know that a great blog post has been written about the same topic, please feel free to add a link to the blog post in the article! There's a lot of great knowledge and information floating about out there - and I think linking to it from the relevant docs articles is a great way to share that knowledge with even more people! 😄 

/Sofie
