### ISSUE TITLE
Broken Edit Link

### ISSUE THREAD

**Issue by blueboxes** [umbraco/UmbracoDocs#271]
https://our.umbraco.org/documentation/reference/using-ioc

This has a broken edit link but no idea where to fix it with pull request?

**Comment by Shazwazza** [comment]
@hemraker pretty sure he means this broken link: https://our.umbraco.org/documentation/reference/custom-controllers

**Comment by blueboxes** [comment]
I was meaning if you click the ocotkitty edit link in the top right of https://our.umbraco.org/documentation/reference/using-ioc it directs you to https://github.com/umbraco/UmbracoDocs/blob/master/reference/using-ioc.md which is not correct you get a github 404

**Comment by ed-parry** [comment]
It looks like this issue is relating to umbraco.org URL. If "reference" has a capital R, the link works fine (I guess it is pulled into the github.com URL through the Edit button?). But if the link has a lowercase R (as in @blueboxes comments), then it pulls that through into the GitHub URL which is case sensitive and is therefore a broken link.

**Comment by ed-parry** [comment]
A quick look at the source suggests this [file](https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco.Site/Views/MacroPartials/Documenation/Breadcrumb.cshtml) is where the fix is required?

**Comment by ed-parry** [comment]
Made a [pull request](https://github.com/umbraco/OurUmbraco/pull/82) to hopefully resolve this issue.

**Comment by hemraker** [comment]
Awesome, thanks a bunch! Will test :)
