### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by kfa-admin** [umbraco/UmbracoDocs#2824]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
https://our.umbraco.com/documentation/Tutorials/Creating-Tables-for-Umbraco-with-PetaPoco

## Describe the issue
I get an Oooops, something broke for the link.

**Comment by sofietoft** [comment]
Ah! Looks like the link in the menu is looking for an `index.md` file.
This doesn't exist in the "Creating-Tables-for-Umbraco-with-PetaPoco" folder - that's why it's giving us the "Ooops" page.

In order to resolve it, the `index-v7.md` needs to be changed to `index.md`.

Would you be up for the task, @kfa-admin ?

**Comment by kfa-admin** [comment]
Yes I will chnage it

**Comment by sofietoft** [comment]
Links it now working.
I will close this issue.

Thanks for reporting @kfa-admin !
