### ISSUE TITLE
Can't restore after cloning to localhost from cloud

### ISSUE THREAD

**Issue by railway17** [umbraco/UmbracoDocs#2897]
Hi, @charlesroper bergmania I am going to clone Umbraco from cloud.
I cloned as visual studio solution and run out (cloned by `UaaS.cmd`).
But after clicking **Restore** button, I am facing below error page with Error message.

```
Dependency Error
The remote API has thrown an exception.

This situation must be fixed before deploy can work.

Time: Sat Nov 21 2020 18:36:07 GMT+0800 (China Standard Time)
```

I am attaching screenshots [here(video)](https://www.dropbox.com/s/r57m12hrdjqars1/bandicam%202020-11-21%2018-31-14-208.mp4?dl=0), [here(image)](https://www.dropbox.com/s/2xe9on65e9h0wjq/Screenshot_1.png?dl=0)
https://www.dropbox.com/s/r57m12hrdjqars1/bandicam%202020-11-21%2018-31-14-208.mp4?dl=0
https://www.dropbox.com/s/2xe9on65e9h0wjq/Screenshot_1.png?dl=0

**Comment by sofietoft** [comment]
Hi @railway17 !
Thanks for reporting the issue.

I'm not sure it's something I can help you with from a documentation point of view though.
Have you had a look in our [Umbraco Cloud Troubleshooting guide](https://our.umbraco.com/documentation/Umbraco-Cloud/Troubleshooting/)? You might be able to find exactly what you need in there.

Otherwise, I'd encourage you, to get in touch through the Support chat which you can find in the Cloud Portal!
Hope it makes sense - do let me know if you need anything further!

**Comment by railway17** [comment]
Hi, @sofietoft 
Thank you for your reply, 
I checked the trouble shooting guide but I have not got the idea from it.
I think I have to talk with support team and it is best solution at this moment.

Thanks again!

**Comment by sofietoft** [comment]
Glad to help!
I'm sure the supporters will be able to help you move forward from this issue.

I'll close this issue for now.
Please feel free to open new issues, should you come across any issues with our Documentation.
Have a great day!
