### ISSUE TITLE
Umbraco.Forms not valid for Umbraco 7

### ISSUE THREAD

**Issue by thenexus00** [umbraco/UmbracoDocs#2906]
Hi there,
Trying to help resolve a spam issue (as Recaptcha v2 in Umbraco forms is being bypassed A LOT of late) I went to use the Form event handler.
The doc says that it is the same in V7 as well as V8 but you get a namespace error with the references in the code example below:
`Umbraco.Forms`

- Is this not valid for Umbraco 7?
- Is there/should there be a version displayed for 7 thats been overiden with the 8 version?
- Does the handle even work in 7?
- Is it something else?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Add-ons/UmbracoForms/Developer/Extending/Adding-an-Event-Handler.md***

**Comment by sofietoft** [comment]
Thanks for the report @thenexus00 !

Let me start by making sure I understand the case here.
You're having some issues with ReCaptcha v2, and want to try to use a Forms event handler instead.
However, following the docs we have on this, you cannot get it to work... Is that correct?

Also, which version of Forms and which version of Umbraco are you using on the setup where you're trying these things out?

**Comment by sofietoft** [comment]
Hi @thenexus00 
I haven't seen any replies here in a while - did you see my last message? 🤔 

Also, I had a closer look at the article you're referring to here and can see that the article is only valid for Umbraco 8.

Sounds like you're using Umbraco 7, is that correct? Because then I suspect that the samples might not work for you.

**Comment by thenexus00** [comment]
> Thanks for the report @thenexus00 !
> 
> Let me start by making sure I understand the case here.
> You're having some issues with ReCaptcha v2, and want to try to use a Forms event handler instead.
> However, following the docs we have on this, you cannot get it to work... Is that correct?
> 
> Also, which version of Forms and which version of Umbraco are you using on the setup where you're trying these things out?

Hi @sofietoft 
In the documentation for the event handler:
https://our.umbraco.com/documentation/add-ons/umbracoforms/developer/Extending/Adding-an-Event-Handler
Also exists when you choose version 7 but you get a variety of errors that seem to be down to the example only being for V8 and not for 7.

**Comment by sofietoft** [comment]
Ah, yes. It is not very clear in the article, that it is only for Umbraco 8.
Also, the dropdown where you can choose between version 7 and 8 only applies to the search, and not the article on the page.

I can see that the article has a tag saying `versionFrom: 8.0.0`, which means it's for Umbraco 8 only, and it doesn't look like there's a version for Umbraco 7.

I'll add a note to the top of the article, making it clearer that it's only for Umbaco 8, to avoid any further confusion on this one.
Thanks for raising a flag on this one!

**Comment by sofietoft** [comment]
Hi! Apologies for the delay here.
I've added a note to the top of the article in question here, in order to make it more clear that the contents and samples in the article are made for Umbraco Forms version 8 or higher.

With that, I'll also close this issue for now.
Please do get back in touch if you have any questions or comments!

And thanks again for raising a flag here!
