### ISSUE TITLE
Recommended Configuration When Deploying to Azure App Service

### ISSUE THREAD

**Issue by capraynor** [umbraco/UmbracoDocs#2991]
## What type of issue is it? (Choose one - delete the others)
Documentation not clear

## What article/section is this about?
https://our.umbraco.com/documentation/getting-started/setup/server-setup/azure-web-apps#recommended-configuration

## Describe the issue

Hi, Umbraco Contributors: 

We have tested the following settings on Umbraco 8.10.1

```
<add
    key="Umbraco.Core.MainDom.Lock"
    value="SqlMainDomLock" />
<add
    key="Umbraco.Core.LocalTempStorage"
    value="EnvironmentTemp" />
```

We've found that these two settings are necessary when deploying Umbraco to Azure App Service (S1, not the shared instance(F1)), especially when doing the "Swap" operation. (Swap between slots) 

But the setup order for these two variables should be like this when doing : 

1. Remove `Umbraco.Core.MainDom.Lock` option.
1.  Set `Umbraco.Core.LocalTempStorage` option to `EnvironmentTemp`.
1.  First-time Deployment to app service
2. Set `Umbraco.Core.MainDom.Lock` option to `SqlMainDomLock`

Same as upgrading Umbraco: 

1. Remove `Umbraco.Core.MainDom.Lock` option
1. Push Upgraded website to Azure App Service.
2. Complete the upgrading process. 
2. Set `Umbraco.Core.MainDom.Lock` option to `SqlMainDomLock`

As a conclusion: 
- Should always set `Umbraco.Core.LocalTempStorage` option to `EnvironmentTemp`. 
  - Or the site will be crashed in target slot when doing swapping operation. 
  - Workaround when the site crashed caused by `Umbraco.Core.LocalTempStorage` not set: re-publish all the contents in backoffice. 
- Should remove `Umbraco.Core.MainDom.Lock` option when doing installing / upgrading work.
  - Or the site will be crashed while it is upgrading database. It will report `System.TimeoutException: Cannot acquire MainDom at Umbraco.Core.Runtime.MainDom.Acquire()`
  - Workaround when the site crashed by not set `Umbraco.Core.MainDom.Lock`: remove `Umbraco.Core.MainDom.Lock`, and restart website. Don't worry your database is leaving untouched if this exception reported. 
- Should set `Umbraco.Core.MainDom.Lock` option back when installing / upgrading completed. 
  - Or **after swapping slot (staging / production)operation completed** the target slot will report the following issue: `System.IO.IOException: The process cannot access the file 'D:\local\Temp\UmbracoData\xxxxxx\NuCache\NuCache.Content.db' because it is being used by another process.`
  - Workaround: restart the target slot will solve this issue, but will cause a website-down for a while. 

We will mostly using the single instance when running Umbraco in App Service. 

We didn't follow [this link](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/medium-umbraco-web-app) to setup our server. We are trying use "Scale Out" directly in a single instance, for convenience. 

Could you please confirm if this is a bug in Umbraco, or this is by design? 

This issue is confusing us for several  days, could you please give a help 

Thousand thanks!

Raynor

**Comment by capraynor** [comment]
Related issue: https://github.com/umbraco/Umbraco-CMS/issues/9517

Related issue: https://github.com/umbraco/Umbraco-CMS/issues/5035

**Comment by sofietoft** [comment]
Hi @capraynor !

Thanks for the very detailed report.
This is not my area of expertise, so I'll pass it along to the team for a review.

Also, I'm a but unsure about what the issue here is exactly.
Is the issue related to what is in the documentation, or is this an issue you're having with the CMS and Azure set up - or perhaps something third?

**Comment by capraynor** [comment]
@sofietoft 
Well this is a complex issue. 

This is related to document, because when I configure according to this document (on azure app service), I will receive an error, saying `System.TimeoutException: Cannot acquire MainDom at Umbraco.Core.Runtime.MainDom.Acquire()`

This is related to product team, because obviously, the workaround was provided by product team. 

After my testing, I think that the Recommended  configurations you provided is useful, but the usage is wrong. 

So, I just reported the symptom to here. 

If I reported this issue in a wrong place, I can close this issue and move it to the right place. You can let me know the correct place to put this issue. 

Thanks for all your effort!

Raynor

**Comment by sofietoft** [comment]
Thanks for providing some more context to this issue - much appreciated.

Now, I agree with you that this is both related to the product and to our documentation.
I've already sent it through to the team here at Umbraco HQ, which means we should get someone to take a look at this issue with the next few weeks.

You're welcome to also create something on the CMS issue tracker if you'd like - make sure to mention this issue there if you decide to do that.

**Comment by Shazwazza** [comment]
These 2x settings should **always** be applied to Azure, see https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps#recommended-configuration

```xml
<add
    key="Umbraco.Core.MainDom.Lock"
    value="SqlMainDomLock" />
<add
    key="Umbraco.Core.LocalTempStorage"
    value="EnvironmentTemp" />
```

The problem you are experiencing when installing/deploying to Azure for the first time is a bug. You should be able to have this applied before you deploy or install Umbraco without issue. I believe this is fixed in recent Umbraco releases. Without these settings you will get all sorts of problems in Azure.

> We will mostly using the single instance when running Umbraco in App Service.
> We didn't follow this link to setup our server. We are trying use "Scale Out" directly in a single instance, for convenience.

You cannot scale out on a single instance this will not work. The docs describe this and require one instance for the "main" editing environment and a 2nd "replica" instance for the front-end scalable environment.

The Microsoft link you mentioned is out of date and also potentially misleading since it's old and not maintained or written by Umbraco.

We have docs on load balancing and scaling, see:

* https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/
* https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/azure-web-apps

**Comment by Shazwazza** [comment]
Just closing this one since the docs are correct. With latest versions of umb you should be able to use SqlMainDomLock from start to finish including during install without having to remove and re-add it, etc...
