### ISSUE TITLE
after installation throwing this error

### ISSUE THREAD

**Issue by sespriye** [umbraco/UmbracoDocs#2995]
Could not load all types from "Our.Umbraco.FileSystemProviders.Azure.Media, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.Composing.IComponent: Could not load type 'Umbraco.Core.Composing.IComponent' from assembly 'Umbraco.Core, Version=1.0.7128.14457, Culture=neutral, PublicKeyToken=null'.
. System.TypeLoadException on Umbraco.Core.Composing.IComposer: Could not load type 'Umbraco.Core.Composing.IComposer' from assembly 'Umbraco.Core, Version=1.0.7128.14457, Culture=neutral, PublicKeyToken=null'.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Extending/FileSystemProviders/Azure-Blob-Storage/index.md***

**Comment by sofietoft** [comment]
Hi @sespriye !

Thanks for the report.
I'm sorry to hear you're having some struggles installing Azure Blob Storage on your website.
I'll need some more details from you, in order to determine how best to help you out here:
- Which version of Umbraco are you running?
- Is the site hosted on Umbraco Cloud?
- When exactly are you getting this error? After completing the entire guide?

**Comment by sofietoft** [comment]
Hi @sespriye !
I haven't heard anything back from you, so I'll go ahead and mark this issue as closed for now.

Should you continue to encounter the same issue, please do let us now and provide some more details about your set up, so we can figure out what might be happening here 💪
