### ISSUE TITLE
Content Type Property Conventions

### ISSUE THREAD

**Issue by KevinJump** [umbraco/UmbracoDocs#316]
There doesn't appear to be anything in the documentation about the 'preset' umbraco properties that do special things.

e.g. 
- umbracoNaviHide
- umbracoUrlAlias
  (see https://github.com/umbraco/Umbraco-CMS/blob/75c2b07ad3a093b5b65b6ebd45697687c062f62a/src/Umbraco.Core/Constants-Conventions.cs#L47) 

quite happy to put something in the documentation not 100% sure where it would live? 

maybe as a child of https://github.com/umbraco/UmbracoDocs/tree/a5eb68c4b4c811a40039710754c47d067d460ad5/Getting-Started/Data/Defining-content ? 

or indeed in this document?

**Comment by greystate** [comment]
This page mentions a couple of them:

https://our.umbraco.org/Documentation/Reference/Routing/routing-properties

**Comment by sofietoft** [comment]
Hi Kevin,
That's an excellent idea! 😁 

I realize it's been quite a while since you added this ticket. 
BUT! If you're still up for it, it'd be amazing if you'd make some documentation for these '_special properties_'! 😄 

Looks like the only one missing is the _umbracoNaviHide_ property: https://our.umbraco.org/Documentation/Reference/Routing/routing-properties

-Sofie

**Comment by marcemarc** [comment]
@sofietoft @KevinJump @greystate  My feeling is that umbracoNaviHide is probably not on the routing-properties documentation page, because it isn't really 'routing' related... it's a convention to use with the IsVisible() IPublishedContent extension method (which we also do not document)...

Suggestion would be to add details of IsVisible convention to the Querying section for IPublishedContent collections, perhaps under a 'Filtering/Querying Conventions' header, 

https://our.umbraco.org/documentation/Reference/Querying/IPublishedContent/Collections

as it's in using the querying of these collections that the convention of filtering by IsVisible would be most likely utilised.

At the point of writing about IsVisible, then it makes sense to explain this uses a property called umbracoNaviHide to be created in order to work...

-Marc

**Comment by greystate** [comment]
Wholeheartedly agree with @marcemarc that `umbracoNaviHide` is better suited to a page (finally!) describing the `IsVisible()` "situation", and the fact that it is totally dependent of that property being present :)

**Comment by marcemarc** [comment]
Added a few lines of text to the querying  IPublished Content collections page: https://github.com/umbraco/UmbracoDocs/pull/622

**Comment by marcemarc** [comment]
@KevinJump @sofietoft @greystate merged in, a historic moment for the documentation umbracoNaviHide is in the docs!
