### ISSUE TITLE
Url toTemplate suggested in Getting Started tutorial is failing

### ISSUE THREAD

**Issue by AlbertoLeon** [umbraco/UmbracoDocs#3169]
I can't access to https://templated.co/retrospect

DNS_PROBE_FINISHED_NXDOMAIN

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/Creating-Basic-Site/Getting-Started/index.md***

**Comment by busrasengul** [comment]
Hey @AlbertoLeon,
You're correct the template site is not working currently. Thank you for raising this up! 
We will check and find either the right URL or try to find a different template to change the URL as soon as possible!

**Comment by busrasengul** [comment]
Hey @AlbertoLeon, 
So it turns out that we website where the template we've used for that tutorial no longer exists 🤷‍♂️As well as being aware of this problem we're also working on updating the whole tutorial with a new template.😊 This is a WIP at the moment. So if you keep an eye on the Creating Basic Site link it will be there shortly ✌
