### ISSUE TITLE
IUserComposer - Is obsolete

### ISSUE THREAD

**Issue by simonantonio** [umbraco/UmbracoDocs#3628]
Visual Studio flags the IUserComposer interface as obsolete - this is used in the following documentation. 

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Implementation/Default-Routing/Controller-Selection/index.md***

---
Instead this seems to be the correct way to setup a Default Controller

In the **Startup.cs**
```
        /// <summary>
        /// Configures the services.
        /// </summary>
        /// <param name="services">The services.</param>
        /// <remarks>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        /// </remarks>
        public void ConfigureServices(IServiceCollection services)
        {
#pragma warning disable IDE0022 // Use expression body for methods
            services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .Build();
#pragma warning restore IDE0022 // Use expression body for methods

            services.Configure<UmbracoRenderingDefaultsOptions>(c =>
            {
                c.DefaultControllerType = typeof(DefaultController);
            });
        }
```

**Comment by p-m-j** [comment]
Configuring services in your startup class (or via convention in your container of choice) makes sense for those implementing sites.

Composers are still around for package developers (no access to startup code) that need access to the container or anyone else that wishes to use composers however IComposer should be used instead of IUserComposer.

IUserComposer which implements IComposer, used to have behavioural differences to other IComposers e.g, IUserComposer instances always ran after ICoreComposer instances. now all IComposers are treated equally.
