### ISSUE TITLE
Add info on what to include in source control

### ISSUE THREAD

**Issue by Myster** [umbraco/UmbracoDocs#366]
What should always be in source control
What should never be in source control
What may or may not be in source control depending on your work-flow.

A discussion I started about this is here: https://our.umbraco.org/forum/using-umbraco-and-getting-started/78957-what-should-i-commit-in-the-umbraco-folder 

I nearly just submitted a PR, but I wasn't sure where to put it, perhaps if a stub were created I could put in the info from the forum, then someone else could check it :-)

**Comment by marcemarc** [comment]
We now have a page that we can update with Source Control info!

**Comment by tlaukkanen** [comment]
Adding a direct link here to that page so that next person saves time from searching it 😅 
[What folders and files should I exclude from my source control repository?](https://github.com/umbraco/UmbracoDocs/blob/main/Getting-Started/Code/Source-Control/index.md#what-folders-and-files-should-i-exclude-from-my-source-control-repository)
