### ISSUE TITLE
Missing information about making sure there's an UmbracoContext (when needed)

### ISSUE THREAD

**Issue by creativesuspects** [umbraco/UmbracoDocs#3682]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Scheduling/index-v8.md***

It's not uncommon for people to use (custom) services in their background task components. When any of these services (or one of the chained dependencies) injects a dependency that relies on `UmbracoContext` (e.g. `MembershipHelper`) you'll get a boot failed error with a `NullReferenceException` when starting the website, because the `UmbracoContext` is not available by default in a background task. So it would be nice if the documentation describes this scenario and how to make sure there's an `UmbracoContext` available, by using `IUmbracoContextFactory`:

```
public class ADemo : IComponent
    {
        private readonly IUmbracoContextFactory _contextFactory;
        private readonly IContentService _contentService;

        public ADemo(IUmbracoContextFactory contextFactory, IContentService contentService)
        {
            _contextFactory = contextFactory;
            _contentService = contentService;
        }

        public void Initialize()
        {
            using (_contextFactory.EnsureUmbracoContext())
            {
                _contentService.GetById(-1);
            }
        }

        public void Terminate() { }
    }
```

**Comment by sofietoft** [comment]
Hi @creativesuspects !

Thanks a bunch for raising this issue - and apologies for the late reply!

Just to make sure I understand the case here:
Due to the fact that the `UmbracoContext` is not available by default in background tasks, it is very common to get the `NullReferenceException` when using services and other things dependant on it - the ´UmbracoContext´.
And that's why you're suggesting to add some docs about this particular scenario and show how to make the ´UmbracoContext´ available.

Did I get that right?

**Comment by creativesuspects** [comment]
@sofietoft That is correct.

**Comment by sofietoft** [comment]
Super. Thanks for confirming 💪 

I'll need to run this by some of our experts, and get back to you!

**Comment by sofietoft** [comment]
Hi again @creativesuspects !

As @p-m-j already suggest, it looks like this is already showed in an example in: https://our.umbraco.com/Documentation/Implementation/Services/#accessing-published-content-outside-of-a-http-request 

How about instead of adding a new sample to the page you're referencing here, we instead link to the existing example? 🤔

**Comment by creativesuspects** [comment]
Hi @sofietoft! Yes, it would be very helpful if the information about the background tasks referred to this documentation: 

https://our.umbraco.com/Documentation/Implementation/Services/#accessing-published-content-outside-of-a-http-request

I think it's quite common for people to use services/dependencies that rely on the `UmbracoContext ` in their background tasks. And the `NullReferenceException` you get when you're not using `IUmbracoContextFactory` is quite vague, so a reference to those docs could be a real time saver.

**Comment by sofietoft** [comment]
I think that's a really good point as well! 💪 

So, how about we add a note to the Scheduling docs on what to do when relying on the `UmbracoContext`, and in that note link over to the example in the Services article?
Perhaps it's something that you'd be up for doing @creativesuspects ? 😄 
We have a set of [contributions guidelines](https://our.umbraco.com/documentation/Contribute/) to get you started!

**Comment by creativesuspects** [comment]
@sofietoft I'll have a look at the guidelines and create a PR for this addition to the docs.

**Comment by sofietoft** [comment]
Sounds great @creativesuspects ! 😄 

I've assigned the issue here to you!
Let me know if there's anything we can assist with in regards to creating the PR 💪

**Comment by creativesuspects** [comment]
@sofietoft I've created PR #3889. I hope this change complies with the guidelines.
