### ISSUE TITLE
URL errors in Umbraco 9.4.1

### ISSUE THREAD

**Issue by wicketbr** [umbraco/UmbracoDocs#3877]
We are seeing an odd issue with the URLs being generated for content. It seems to happen with child content and lower. In addition to the correct path to the document, the URL is including the alias of the top level of the site as well. For example, I have a site where the top of the site has a name of "EM CMS". The main URL to that site is fine (https://cms.em.wsu.edu/). I have a child page under the site named Instructions that shows a URL in the BackOffice under links of https://cms.em.wsu.edu/instructions/. However, when navigating the site the link gets changed to https://cms.em.wsu.edu/em-cms/instructions/ which breaks navigation. If I clear the Umbraco cache on the server things work again until the child page is republished, which causes the URL to be generated with the parent alias again. This is an urgent issue for us.

**Comment by sofietoft** [comment]
Hi @wicketbr !
Thanks for reporting this issue - sure sounds like a frustrating one! 🤔 

So for my understanding, whenever child pages on your website are published, the name of the home node on your website is added to the public link, which causes issues for the site.
Is that correct?

We have some docs on [URL management](https://our.umbraco.com/documentation/Reference/Routing/URL-Tracking/) and [Web Routing](https://our.umbraco.com/documentation/Reference/V9-Config/WebRoutingSettings/) that is might be worth for you to check out.

**Comment by wicketbr** [comment]
That is correct. I have reached out for help in the forums as well, but have not heard anything there yet.

**Comment by sofietoft** [comment]
Thanks for confirming!

We've tried running some tests on the latest version of Umbraco, and we can't seem to replicate the issue 🤔
I'd suggest that you double-check your rewrites, and possibly also the articles I link to previously - if you haven't already.

I'm afraid that's as far as I'm able to go here, as this Issue Tracker is meant to be used for documentation-related queries.
The Forums or getting in touch with our support using contact@umbraco.com is really your best bet.

I hope everything works out!
I'll close this issue here for now - feel free to get back in touch, if something docs-related should come up.

**Comment by wicketbr** [comment]
I've confirmed that this issue has to do with the WebRouting / DisableRedirectUrlTracking setting. If I set DisableRedirectUrlTracking to true the problem goes away, but then I lose URL redirection. And, if I leave it set to false, when the URLs get messed up if I go into Settings / Published Status and click Reload for the Memory Cache, the URLs are correct again.

**Comment by wicketbr** [comment]
I've also updated my forum post at https://our.umbraco.com/forum/using-umbraco-and-getting-started/108648-url-errors-in-umbraco-941 with this info. So, if you want to close this that's fine. I didn't realize this area was only for documentation.
