### ISSUE TITLE
Unsubscribe from event typo in docs

### ISSUE THREAD

**Issue by TutaBugarin** [umbraco/UmbracoDocs#3912]
Snippet from page:

_When you subscribe to static events you should also unsubscribe from them when Umbraco shuts down, see the Terminate() method in the example using the -+ syntax to achieve the unsubscribing._

Shouldn't it be -= instead of -+ ?

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Fundamentals/Code/Subscribing-To-Events/index.md***

**Comment by eshanrnh** [comment]
Hey @TutaBugarin 

Thanks for flagging this issue.
Seems like the typo should definitely be corrected🙈 Great find!

Would you be up for making the PR? 😄 Let me know.
We have some contribution guidelines here: https://our.umbraco.com/documentation/Contribute/

Otherwise, I'll make sure it's added to our task list 💪

**Comment by eshanrnh** [comment]
This issue is now fixed.
