### ISSUE TITLE
Umbraco.Tags cannot be deleted

### ISSUE THREAD

**Issue by deliberaligiacomo** [umbraco/UmbracoDocs#408]
I have a DataType called `Multi language Tags` that is a `Vorto` property based on `Umbraco.Tags`.

Once I have added a tag, I can't remove it. If I click in the cross to delete it, nothing happens. Any ideas?

<img width="235" alt="screen shot 2016-12-20 at 18 31 20" src="https://cloud.githubusercontent.com/assets/4717227/21361035/996982fc-c6e2-11e6-9736-4bc7cfec230c.png">

**Comment by hemraker** [comment]
Hi @deliberaligiacomo this is the repository for the Umbraco documentation. Might be a good idea to post the issue on the [umbraco forum](https://our.umbraco.org/forum/), since you are using the Vorto package it might be a good idea to post it to the Vorto forum. You can find that at the bottom of the [Vorto project page](https://our.umbraco.org/projects/backoffice-extensions/vorto/)

Hope that make sense 😃 

All the best
Rune

**Comment by Al-Sharif** [comment]
Hi all, in umbraco.controllers.js:15533 
`if (!$scope.model.config.storageType || $scope.model.config.storageType !== 'Json')` this condition related for each array of tags in one post.
I've changed `Json` to `Csv` while VortoTags returning json and **solved** for me. 

but i need to know if there's any risk for this change? and how can change storageType for this dataType?
