### ISSUE TITLE
This guide seemse outdated for Umbraco 10

### ISSUE THREAD

**Issue by MEbsen** [umbraco/UmbracoDocs#4192]
Following this guide, everything works fine until you start up the solution. It is clear that some parts of Umbraco still work with those URL changes but others like frontend filers no longer respond to these path changes, and you will now end up with multiple 404 and a blank page if you try to access the back office.
Even content pages will show up as 404 pages.

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Security/Security-hardening/index.md***

**Comment by MEbsen** [comment]
Oh and I tested the Guide for Umbraco 9.5.2 as well, here it works fine.

**Comment by sofietoft** [comment]
Fantastic @MEbsen !
Thanks a bunch for the very detailed explanation - much appreciated!

The Issue has been sent to our devs for review 💪

**Comment by MEbsen** [comment]
Just found this issue, it looks related: https://github.com/umbraco/Umbraco-CMS/issues/12593

**Comment by bergmania** [comment]
The intension is this should work the same in umbraco 9+10. But as mentioned on https://github.com/umbraco/Umbraco-CMS/issues/12593, the feature is currently broken.

**Comment by sofietoft** [comment]
Hi @MEbsen !

I'm sorry for the delay on this one!

I've had a look at the [CMS Issue referenced by Bjarke](https://github.com/umbraco/Umbraco-CMS/issues/12593) ☝️ 
I can see that the Security Hardening article was [updated in September last year](https://github.com/umbraco/UmbracoDocs/commits/121ca57153a359b28293f3b59c86e25a90f2b94c/Reference/Security/Security-hardening/index.md?browsing_rename_history=true&new_path=umbraco-cms/reference/security/security-hardening.md&original_branch=main).

Would you be up for checking it out, and letting me know whether or not it helps you resolve what you've been running into here?
Otherwise, there are also a couple of recommendations in the CMS thread, that you could check out!

**Comment by sofietoft** [comment]
Hi @MEbsen 

As there hasn't been any activity on this one in a while, I'll close it down for now.
Please do not hesitate to get back in touch, should you continue to experience any issues with this.
