### ISSUE TITLE
Broken Link to Configuring Courier Page

### ISSUE THREAD

**Issue by mitchstewart** [umbraco/UmbracoDocs#421]
If you click the Configuring Courier link on page https://our.umbraco.org/documentation/products/umbracocourier/Architecture/Index/, the link directs to Architecture/Index/Configuration when it needs to direct to Architecture/Configuration.

**Comment by mitchstewart** [comment]
Actually, all of the links on the above page are broken.

**Comment by sofietoft** [comment]
Hi Mitch,
Thanks for raising this issue! 😄 

If you go to 
https://our.umbraco.org/documentation/Add-ons/UmbracoCourier/Architecture/
Instead of
https://our.umbraco.org/documentation/products/umbracocourier/Architecture/Index/

All the links seems to be working correctly.

I know it's been a while since you made the issue here, but do you happen to know how you ended up on https://our.umbraco.org/documentation/products/umbracocourier/Architecture/Index/ (with /Index in the end)? 😁 

-Sofie
