### ISSUE TITLE
Security Doc: Better documentation on OAuth or AD authentication for members or backoffice user.

### ISSUE THREAD

**Issue by biapar** [umbraco/UmbracoDocs#422]
Better documentation on how to configure OAuth or AD authentication for members or backoffice user.

**Comment by sofietoft** [comment]
Hi there,
Thank you so much for contributing! 😁 

Since your request this article has been updated: https://our.umbraco.org/Documentation/Reference/Security 

A lot of information about both OAuth and AD authentication has been added.
If you still feel something is missing, please let us know!

Thanks again for helping us improving our Docs!
-Sofie
