### ISSUE TITLE
Explain Forms RCL files better

### ISSUE THREAD

**Issue by jemayn** [umbraco/UmbracoDocs#4405]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[Umbraco Forms adding a custom field type](https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-fieldtype#partial-view)

## Describe the issue

Had this question on the community discord today - it isn't really explained that the view folders no longer exist after the Forms package was made into an RCL - would be good to explain how it works now and point to the assets zip on the forms page:
https://our.umbraco.com/packages/developer-tools/umbraco-forms/

**Comment by AndyButland** [comment]
Thanks for the report @jemayn.  We do have this information documented but I agree it may not be easy to find.

The reasons for the RCL are in the upgrade notes [here](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Installation/Version-Specific#views-and-client-side-files).

And we have information about the zip file for the default theme at the start of the "theming" section [here](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Themes/).

I'd suggest at a minimum @eshanrnh we should add a bit to the section Jesper has pointed out, i.e. [here](https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-fieldtype#partial-view), extending the copy of that section to:

Then we will start building the view for the default theme of the form at `Views\Partials\Forms\Themes\default\FieldTypes\FieldType.MyCustomField.cshtml.`

The file name for the partial view should match the value set on the `FieldTypeViewName` property.

If working with Umbraco 9 or earlier versions, you'll find the `Views\Partials\Forms\Themes\default\` folder on disk, and can create the files in there.  For Umbraco 10, now we've moved to [distributing the theme as part of a Razor Class Library](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Installation/Version-Specific#views-and-client-side-files) the folder won't exist, but you can create it for use for your custom field type.  If you would like to refer to the partial views of the default theme, you can download them as detailed in the [theming documentation](https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Themes/).

---

If you see any other improvements that'll help with this, please feel free to make them too.  However I'd suggest avoiding adding multiple links to the zip file for download, as we will update this as new versions are released, so in order to maintain it'll be easier to have just one place we link out to it.

**Comment by eshanrnh** [comment]
[The article](https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/adding-a-fieldtype#partial-view) now contains the information as mentioned above. @jemayn Is there anything else we can do to improve the article? 😃

**Comment by jemayn** [comment]
@eshanrnh Thanks! Nothing else off the top of my head 🙂
