### ISSUE TITLE
Broken: all links for Courier Architecture

### ISSUE THREAD

**Issue by alirobe** [umbraco/UmbracoDocs#443]
All header links are broken @ https://our.umbraco.org/documentation/products/umbracocourier/Architecture/Index/

'index' seems as though it should not be created as a folder.

Also, the "github edit" button is broken.

**Comment by sofietoft** [comment]
Hi,
Thank you so much for pointing this out 😁 

Please refer to this issue: https://github.com/umbraco/UmbracoDocs/issues/421

I'm very interested to know, how you ended up on https://our.umbraco.org/documentation/products/umbracocourier/Architecture/Index/ instead of the correct https://our.umbraco.org/documentation/Add-ons/umbracocourier/Architecture/

-Sofie
