### ISSUE TITLE
Better Explanation and Example for Media service on Umbraco 10+

### ISSUE THREAD

**Issue by biapar** [umbraco/UmbracoDocs#4440]
***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Reference/Management/Services/MediaService/Index.md***

This example don't work for U10.

`media.SetValue(_mediaService, _mediaUrlGeneratorCollection, _shortStringHelper, _contentTypeBaseServiceProvider, Constants.Conventions.Media.File, subscriberModel.file1name, stream);`

Error: no method set value accept 7 arguments
I've added Umbraco.Extension but the error is still there.

**Comment by sofietoft** [comment]
Hi @biapar 
Thanks for reporting this issue.

The article you are referring to is under the "Services" section, and this is a section that we no longer maintain since the release of Umbraco 10. 
The reason behind this is due to the fact that we already have [auto-generated API docs](https://apidocs.umbraco.com/v10/csharp/api/Umbraco.Cms.Core.Services.html?_ga=2.50476911.7355902.1665384589-357517136.1639645836) covering these services. There you will also be able to find a complete list of methods within the [IMediaService](https://apidocs.umbraco.com/v10/csharp/api/Umbraco.Cms.Core.Services.IMediaService.html).

We're currently working on a ["Samples" project](https://github.com/umbraco/Umbraco.Docs.Samples) containing most samples from the documentation.
I can see that the [MediaService samples](https://github.com/umbraco/Umbraco.Docs.Samples/blob/develop/Umbraco.Docs.Samples.Web/Services/MediaServiceSamplesController.cs) are added there - and that's a Umbraco 10 project!

Using those resources, I hope you're able to resolve this issue you're running into 💪

**Comment by biapar** [comment]
Don't work also for U10. I followed that example, too. I spent all one day to try.

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/661517/194820899-838a9ba8-38b5-4811-8416-51cd5605687f.png">

If you want, this is my class:

`
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/661517/194821029-55472106-9d13-4bb1-aa30-aecc3369c54e.png">
`

**Comment by biapar** [comment]
The strange thing is that Visual Studio 2022 suggest Umbraco.Exstensions

**Comment by sofietoft** [comment]
Thanks for checking 💪 

I'm sorry to hear that the sample in the Sample Project also didn't do the trick here 🤔 
I'm afraid I will not be able to help with debugging your code, as that's outside the scope of the docs here - I'd have to refer you to the [Forums on Our](https://our.umbraco.com/forum/) or the [Umbraco Support](mailto:contact@umbraco.com).

I'll double-check that the sample in the Samples Project is up to speed, and talk to the team about the samples in the MediaService article. Could be that something has been overlooked!

**Comment by biapar** [comment]
I solved the syntax error.

This is the code:  

`media.SetValue(_mediaFileManager, _mediaUrlGeneratorCollection, _shortStringHelper, _contentTypeBaseServiceProvider, Constants.Conventions.Media.File, subscriberModel.file1name, stream);`

In Umbraco 10.2.1 we have to import Umbraco.Extesions

This namespace there is'nt into the example and documentations.

**Comment by sofietoft** [comment]
Aha! Very interesting 🤔 

Thanks a million for sharing what you learned here.
I'll be sure to share it with the ones currently working on the Samples Project so we can get it all updated correctly 💪

**Comment by Jeavon** [comment]
In v10+, `Umbraco.Extensions` is a global `using` so you should not need to import it. You can see in the Samples project it's working perfectly

**Comment by biapar** [comment]
Hi, I'm not agree. I use it into a my external class called by the controller. If I remove Umbraco.Extesions, I've the error on the SetValue. 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.IO;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Notifications;
using Umbraco.Cms.Core.Services;
using System.IO;
 
using Umbraco.Cms.Core.Web;
using Examine;
using UGWCareRedTechExtension.Models;
using Umbraco.Cms.Core.Security;
using System.Diagnostics.Eventing.Reader;
using Serilog;
using Polly;
using UGWCareRedTechExtension.Interfaces;
using Newtonsoft.Json;
using UGWCareRedTechExtension.Business.AWS;
using Umbraco.Cms.Core.PropertyEditors;
using Umbraco.Cms.Core.Strings;
using Umbraco.Extensions;
using static System.Net.WebRequestMethods;
```

**Comment by biapar** [comment]
I wrote the namespaces that I import in the class.

**Comment by sofietoft** [comment]
Hi @biapar 👋 

Just wanted to let you know that changes have now been committed to the MediaService article: https://github.com/umbraco/UmbracoDocs/pull/4451

Thanks again for reporting your findings - it's very much appreciated 😎
