### ISSUE TITLE
BootFailedException error when adding the package

### ISSUE THREAD

**Issue by acceliance** [umbraco/UmbracoDocs#4541]
Hi,

When adding the starter kit inside an empty umbraco projet, i get the error:

-> **Umbraco.Cms.Core.Exceptions.BootFailedException: The input string '499.0' was not in a correct format.**

thank you forheping

***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/main/Tutorials/Starter-kit/Lessons/1-Customise-the-Starter-Kit/index.md***

**Comment by sofietoft** [comment]
Hi @acceliance !
Sorry to hear that you're running into some issues with the StarterKit here.
Could you give me a bit more information about what versions of Umbraco you're trying out the StarterKit on?

**Comment by acceliance** [comment]
Hi,

I use umbraco v10 and v11 with starterkit v10

**Comment by acceliance** [comment]
To reproduce the bug, create empty umbraco projet, add starterkit in visualstudio, run => bug

**Comment by sofietoft** [comment]
Thanks for the details @acceliance 💪 

I'll make sure we give this a thorough test!

**Comment by eshanrnh** [comment]
Hi @acceliance,

I tried following your steps but unfortunately could not replicate the issue. Can you take a look and let us know if you did anything differently?
 
https://user-images.githubusercontent.com/82437098/199230853-104d69e7-fbd2-4e6c-95dd-6c9b2b883825.mp4

**Comment by acceliance** [comment]
[UmbracoTraceLog.PC-JOSE-DEV.20221103.json.txt](https://github.com/umbraco/UmbracoDocs/files/9929942/UmbracoTraceLog.PC-JOSE-DEV.20221103.json.txt)

I followed the exact procedure and get the error, plese see logs.

regards, josé

**Comment by sofietoft** [comment]
Hi @acceliance 
Sorry to hear that you're still struggling with installing the StarterKit on your Umbraco project.

I'm afraid we've gotten as far as we can here, as we haven't been able to reproduce the issue.
I'd recommend that you report this on the "Starter Kit" Issue tracker instead: https://github.com/umbraco/The-Starter-Kit/issues 

Otherwise the [Forum on Our](https://our.umbraco.com/forum/) as well as the [Community Discord channel](https://community.umbraco.com/get-involved/community-discord-channel/) are also great ways of getting help 💪 

I'll be closing this one for now!
