### ISSUE TITLE
Broken links, incorrect links and search not finding known documentation

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/UmbracoDocs#4798]
I don't know if it's because it's still a work in progress, but I feel like there are a lot of things with the move to the new documentation, that gives users a hard time finding what they are looking for. 

**301 Redirects**
On forums, Github discussions, stack overflow and a lot of other places, there are links, that now are broken. 

Take this link found in a Github discussion
https://our.umbraco.com/Documentation/Add-ons/Umbraco-Deploy/Deploy-Settings/index-v8#ignore-broken-dependencies
Because v9 has been removed from old docs site, the correct link is now
https://our.umbraco.com/Documentation/Add-ons/Umbraco-Deploy/Deploy-Settings/#ignore-broken-dependencies

These broken links should of course be redirected

**Links to corresponding new documentation**
If I follow a link or a google search, I will probably end up on the old documentation for a while yet, so if I end up on for example this page
https://our.umbraco.com/documentation/Implementation/Custom-Routing/

I then click on the link for documentation, but I'm sent to the frontpage of the new documentation site, and not directly to the corresponding subject, which would be this page
https://docs.umbraco.com/umbraco-cms/implementation/custom-routing

**Missing documentation, not indexed content or broken search**
I don't know if it's because the documentation for this is missing, or something is not right with the search, but when looking for the documentation of Umbraco Deploy Settings, specifically the IgnoreBrokenDependencies, i was at this page
https://our.umbraco.com/Documentation/Add-ons/Umbraco-Deploy/Deploy-Settings/#ignore-broken-dependencies

I Clicked to go to v9+ documentation, ended up on the frontpage, and tried searching for 'Ignore', but that did not return any results. 

I feel that it's important that documentation is really easy to find, also after it has been moved. Users shouldn't have to guess on what to do next, this will frustrate them and some might give up, which is not great if they are new to Umbraco. 

Just some reflections and suggestions to some things that needs some attention.

**Comment by sofietoft** [comment]
Thanks a bunch for all the feedback @MichaelNielsenDK ! It is highly appreciated 🙌 

We are aware that there are still a few hiccups here and there, and we are also still learning how best to utilize the new platform.

**301 redirects**
Yes, some broken links will occur when the links are referencing a specific version of an article.
This is something we are currently handling on a case-by-case basis, but I am also looking into whether it's possible to make a more generic rewrite for these version-specific ones!

In the meantime though, it would be great if you could keep reporting the broken links!

**Links to corresponding new documentation**
We've requested Google to index the new site, and we can see that it is slowly starting to happen - which is great!

For now, it is intentional that the link to the new site in the pink box on Our links to the landing page.
It would indeed make sense that the link would be to the corresponding article on the new site - it is something we're taking under consideration, should the indexing on Google continue to be dragged out!

**Missing documentation, not indexed content, or broken search**
This is actually an issue we've seen a couple of times already, and I think I've managed to find the root cause.
The formatting of the meta description is different on the new platform compared to the one we used on Our. This wasn't properly cleaned up, which resulted in some articles not being part of the search! 
That should be cleaned up later today or tomorrow, as soon as the PR is merged 💪 🤞 
Again, it's a learning process for us all! 😄 

Thanks again for providing all the feedback! We really appreciate it, as it results in making the platform even better 🙌

**Comment by MichaelNielsenDK** [comment]
I've already seen the direct links a couple of places, and it works so much better, good work 💪

**Comment by sofietoft** [comment]
Hi @MichaelNielsenDK !

I'll be closing this issue, as I think the redirects and rewrites from Our to the new docs platform is in a pretty good place.
We've also started being a little more aggressive towards Google, having it ignore the Docs on Our - at least for the next few days 🤞 

Please do keep reporting any broken links or other strange things you might run into 🙌 
Have a fab' Friday!
