### ISSUE TITLE
Gitbook Search, doesn't find exact matches in code snippets?

### ISSUE THREAD

**Issue by mistyn8** [umbraco/UmbracoDocs#4816]
## What type of issue is it? (Choose one - delete the others)
Gitbook Search not working

## What article/section is this about?
multiple...

## Describe the issue
Not sure if it's just code snippets.. but gitbook search seems lacking when searching for code keywords

Couple of examples here where the exact search term is in the code snippet greyed out below the search box but not found by gitbook?

`backOfficeAuthenticationBuilder`
![image](https://user-images.githubusercontent.com/12418214/211669194-8b44e025-6b7d-447d-b110-7c641c0c568c.png)
`OnAutoLinking`
![image](https://user-images.githubusercontent.com/12418214/211669470-9f411299-43ef-49af-a68b-9ca790389dcd.png)

**Comment by sofietoft** [comment]
Thanks a bunch for reporting this @mistyn8 ! 💪 
We have been seeing some strange behavior regarding the search on the new docs site.
So far, we have concluded that the format of the meta description added is correct - otherwise a page will not be included in the search.

Doesn't look like that's an issue with all articles referencing "backOfficeAuthenticationBuilder" or "OnAutoLinking" though, so I'll do some more digging and see what I can find!

**Comment by sofietoft** [comment]
I made some changes to the articles referencing the two terms you've mentioned in this issue: https://github.com/umbraco/UmbracoDocs/pull/4818

When I search the site now, I am able to find all those articles.
The issue was two things: 
- Incorrect formatting of the meta description
- Errors/warnings in the markdown

I'll make sure we check these things carefully going forward 💪

**Comment by sofietoft** [comment]
I'll be closing this issue for now.
I've made another PR that removes all redundant YAML tags (https://github.com/umbraco/UmbracoDocs/pull/4854), which should take care of the remaining search related issues 💪 

Thanks again for reporting your findings here @mistyn8 , and helping us get closer to a solution 😄 

Cheers!
