### ISSUE TITLE
Enable Dark Mode

### ISSUE THREAD

**Issue by myrashed** [umbraco/UmbracoDocs#4976]
Discussion

What about enabling `Dark Mode` for Documentation site?

[(**Gitbook Space customization => Dark Mode** )](https://docs.gitbook.com/tour/customization/space-customization)

**Comment by sofietoft** [comment]
Thanks for raising this @myrashed ! 💪 

We are aware that dark mode/theme is a very popular feature, and you're not the first to ask this 😄 
The GitBook feature you're linking to though will enable dark mode for the entire site and for everybody.

What would be ideal here, is a toggle that enables the reader to switch between dark or light mode when using the docs.

I've raised a feature request with GitBook: https://github.com/GitbookIO/community/discussions/10 
Feel free to upvote it!

**Comment by myrashed** [comment]
Thanks for the feedback @sofietoft :)

**Comment by alina-tincas** [comment]
Hi @myrashed 👋 

Since May 26th Gitbook has created this dark mode feature and we are also using it on our documentation:
![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/1bbb195b-1622-4184-8571-c5d8a01bf98e)
![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/7467d2fa-90a8-4ed0-b505-bff7f7fd1b72)

Therefore I will close this issue. Thank you again for bringing this up 🙌
