### ISSUE TITLE
Missing documentation: Language files are no longer available on disk

### ISSUE THREAD

**Issue by greystate** [umbraco/UmbracoDocs#5008]
This paragraph describes how to add a new translation of the UmbracoForms UI:

https://github.com/umbraco/UmbracoDocs/blob/b896aa17dd0620092edf63925cf9b62cc7aa0988/10/umbraco-forms/developer/localization.md?plain=1#L11

But since v10 (I think?) the `/App_Plugins/UmbracoForms` folder is (much like the `/Views/Partials/Forms` folder) shipped as _RCL_ with no apparent way to get a copy of the files, like it's possible with the view files for the 'default' theme.

EDIT: I've not verified this with the "retail" version of UmbracoForms - I have just seen this on Umbraco Cloud projects' included Forms.

**Comment by greystate** [comment]
Great - it's not just me then 😁 

So the problem then goes: The language files for the CMS are located in the open source project - but the Forms files (I assume) are inside the closed source project... 🤔

**Comment by sofietoft** [comment]
Hm! That's a great question actually 🤔 

We might need to bring some Forms experts on board here.
Let me ping @AndyButland on this one!

**Comment by AndyButland** [comment]
Thanks for raising the issue @greystate.  Unlike with the views - you can actually dig the language files out of the NuGet package if you know or figure out where to look.  

If you open up the NuGet package for the static assets either locally, or online - e.g. via [this link](https://nuget.info/packages/Umbraco.Forms.StaticAssets/11.0.3) - you can open up the `staticwebassets` file and find the files that are virtually loaded into `AppPlugins`.

But I take the point of course that this isn't obvious.  I think rather than creating another zip file that we'll have to maintain separately, I'll add details of how you get access to the language files from the NuGet package to the docs.  It's still arguably a little more complicated, but if it's documented it should be straightforward enough, and means we avoid having to maintain the information in two places.

**Comment by greystate** [comment]
Thanks for the info @AndyButland 👍 

I think it'll be fine just describing how to get those files - I went through getting the theme files yesterday, and once I discovered "oh - they're not here??", I went to the docs and found the link to download them, so anyone finding the need to add another translation will hopefully find the docs article and manage to get on from there.
