### ISSUE TITLE
Missing pages & redirections from old documentation versions

### ISSUE THREAD

**Issue by ewuski** [umbraco/UmbracoDocs#5078]
## What type of issue is it? (Choose one - delete the others)
Missing pages in the documentation.

## What article/section is this about?
[(link here)](https://docs.umbraco.com/welcome/v/10.x-lts/umbraco-cms/reference/searching/examine/indexing)

## Describe the issue
The documentation referenced by the link above was fairly new (re v10 & v11) and even though the structure changed it would be good to redirect old urls to the new urls. Currently lots of links referencing the documentation are broken and it is difficult to find the page that was originally referenced. Example here: https://github.com/umbraco/Umbraco-CMS/issues/13683

It doesn't help developers trying to work and resolve issues in v10 & v11.

**Comment by sofietoft** [comment]
Thanks for reporting this @ewuski !

Hopefully only links targeting the v10 docs specifically are involved here?
If other links are involved as well, please do report them 🙏 

I'm afraid there isn't much we can do, to redirect the old links targeting the v10 site.
I'll make sure to dive a little deeper into it after the Easter holidays, but I did investigate this before we completed the restructure, which is why I don't want to promise too much here. I'll see what I can do though 🙌

**Comment by alina-tincas** [comment]
Hi @ewuski I have discussed this further with our team, however as Sofie mentioned we are unable to redirect all old links targeting v10 sites. We have done some restructuring previously for our documentation, therefore you might have some broken links, however now we have everything in place. So from now if you experience any broken links with our new structure (umbraco-cms/**v/10.latest-lts**/ ) then please report them and we can take it from there 🙏 

Going forward our suggestions would be to do a search in the cms documentation for the version you are trying to look for here: https://docs.umbraco.com/umbraco-cms/ and then when you will get some results with the correct links for our documentation (for example if you look for "examine" you will get a result to the correct article)

Thank you for understanding and thank you again for bringing this to our attention 🙌
