### ISSUE TITLE
Explain default value for Deploy settings

### ISSUE THREAD

**Issue by jemayn** [umbraco/UmbracoDocs#5102]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
[(docs link)](https://docs.umbraco.com/umbraco-deploy/deploy-settings#relationtypes)

## Describe the issue

Trying to debug some issues I'm having with relations not being deployed between environments - found the above linked deploy setting mentioned, but I don't see any mention of what the Deploy does if this section is left blank.

Even if it just ignores the relations, then that is fine - but would be nice to know! 🙂

**Comment by sofietoft** [comment]
Thanks for raising this @jemayn 💪 

Just to be sure I understand:
Are you asking what the **default value** of this configuration is?
Or, are you asking what happens if the value of the config is **left blank**?

**Comment by AndyButland** [comment]
The missing part is kind of documented [here](https://docs.umbraco.com/umbraco-deploy/troubleshooting#review-relation-types-included-in-deploy-operations), but it should be noted on the configuration page of course.

I'd suggest adding a line to the end of the [Relation Types configuration section](https://docs.umbraco.com/umbraco-deploy/deploy-settings#relationtypes) saying:

If this setting is left blank, as of Deploy 10.1.2 and 11.0.1, the two relation types used for usage tracking are omitted.  These are rebuilt by the CMS following a save of an item in the target environment and so don't need to be transferred.  As such, unless you have specified otherwise, the effective default configuration is:

```json
"RelationTypes": [
    {
        "Alias": "umbDocument",
        "Mode": "Exclude",
    },
    {
        "Alias": "umbMedia",
        "Mode": "Exclude",
    }
],
```

**Comment by jemayn** [comment]
@AndyButland thanks for the quick response!

What about other relationtypes, do they default to Exclude, Weak or Strong if not specified in the config? 🙂

**Comment by AndyButland** [comment]
It's considered as "Weak".  I've updated my suggested documentation addition above.

**Comment by jemayn** [comment]
That's perfect, thanks a lot Andy!

I have no more questions, your suggested edit above would fix this issue.

**Comment by jonat123** [comment]
@jemayn Just want to let you know that the documentation has been updated with Andy's comment :) 
- https://docs.umbraco.com/umbraco-deploy/deploy-settings#relationtypes 

I will close down this issue 😄

Have a great day!
