### ISSUE TITLE
Run Umbraco on macOS/Linux for better understanding and also SEO

### ISSUE THREAD

**Issue by DanielOberlechner** [umbraco/UmbracoDocs#5306]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/running-umbraco-on-a-mac

## Describe the issue
macOS and Linux get treated as the same. I wanted to figure out how to run UmbracoCMS on Linux but couldn't find it.
Later on I figured out Linux and macOS Documentation are the same.

In my opinion there is a difference between mac and linux and it should contain a name similar to this:
Run on macOS/Linux for better understanding.

Maybe I'm just a dork, but I could figure for other people this could be misleading as well.

Kind regards,
Daniel Oberlecher from Italy

**Comment by sofietoft** [comment]
Thanks for reporting this @DanielOberlechner !

I see how this article might be a bit too specific to macOS, when it could, in fact, be made more generic 🙈 

Our docs our open source - perhaps you'd be up for making some adjustments to the article yourself? 😄 

Otherwise I'll add it to our task board here, and we'll take a look over the coming weeks 💪

**Comment by DanielOberlechner** [comment]
@sofietoft 
Thats kind of you, surely I would like to make a adjustment.
Hope somebody could confirm the changes that I make, because I'm not native English speaker and also not topnotch with everything related to IT but I would like to try to make it more generic. 

I'll report here today when I've made the changes!

Kind regards,
Daniel
