### ISSUE TITLE
Methods which are marked obsolete should have information stating so

### ISSUE THREAD

**Issue by matthewcare** [umbraco/UmbracoDocs#5394]
When a method gets marked as obsolete in code, the documentation isn't updated to reflect that.
Example
This PR obsoletes all XPath queries
https://github.com/umbraco/Umbraco-CMS/pull/14372/
but the documentation still lists these methods as "usable".
https://docs.umbraco.com/umbraco-cms/reference/querying/umbracohelper

Realisitcally, methods that are marked as obsolete should be either removed from the documentation, or have information to explain that they will be removed, with an example of how to update the code if someone is already using it.

I would favour the information approach, so people can still search the documentation for what they shoud be doing to update their code.

**Comment by alina-tincas** [comment]
Hi @matthewcare thank you for bringing this up! 🙌 

We will look into this as soon as we can, and if you are up for it, you are also welcome to [contribute ](https://docs.umbraco.com/welcome/contribute/getting-started) to our documentation 👍

**Comment by alina-tincas** [comment]
Hi @matthewcare I have created a PR for this issue here #5501. With this PR, a warning note has been added with content that it is currently obsolete and is scheduled to be removed in v14. 

I have also asked the CMS team if there is an alternative for XPath, however, currently, there isn't. They are currently working on an alternative but have no ETA, so when we have more details about this, the documentation will be updated accordingly. 

As the PR has been merged, I am closing this issue. Thank you again for bringing this to our attention 😊 🙌
