### ISSUE TITLE
Blogpost about Block grid assumes ModelsBuilder

### ISSUE THREAD

**Issue by berendvervelde** [umbraco/UmbracoDocs#5544]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
https://umbraco.com/blog/deep-dive-block-grid-editor-part-1/

## Describe the issue
In 'Rendering Block Grid Content' the code '@await Html.GetBlockGridHtmlAsync(Model.MyGrid)' will only work if you are using the ModelsBuilder but the post does not specify this.
Note that the tutorial https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor does show the ModelsBuilder  and non-ModelsBuilder code, but the blog post shows up higher in the Google results.

**Comment by alina-tincas** [comment]
Hi @berendvervelde 👋 

Thank you for opening this issue, however, the blog post is 1 year old so in this case, we cannot do anything about it. The blog posts are used to make know that we have some new features (in this case block grid and how to get started from scratch). Then if there are new features or content after the blog post, then the documentation is updated but not the blog posts.

The documentation is always updated with new content and features and we always recommended to check the documentation instead of the blog posts (especially if the blog posts are few months old). 

It is also mentioned in [this blog post:](https://umbraco.com/blog/umbraco-111-release/#:~:text=If%20you%20haven%E2%80%99t%20tried%20it%20in%20Umbraco%2011%20and%20want%20to%20test%20out%20the%20new%20Property%20Editor%20we%20just%20published%20a%20Deep%20Dive%20blog%20post%20that%20takes%20you%20through%20all%20the%20basics.%20You%20can%20also%20dig%20into%20the%20extensive%20documentation%20for%20the%20Block%20Grid%20Editor.) "If you haven’t tried it in Umbraco 11 and want to test out the new Property Editor we just published a[ Deep Dive blog post that takes you through all the basics](https://umbraco.com/blog/deep-dive-block-grid-editor-part-1/). You can also dig into the extensive [documentation for the Block Grid Editor](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor)**"

I hope this makes sense, otherwise please let me know! 😊
