### ISSUE TITLE
Reduced website's usability due to broken Links

### ISSUE THREAD

**Issue by Smartmind12** [umbraco/UmbracoDocs#5546]
## What type of issue is it? (Choose one - delete the others)

Wrong documentation links leading to 404 (Page not found) errors.

## What article/section is this about?

This was found in multiple pages of the documentation

## Describe the issue
these are the following broken links:
[Versions and updates](https://docs.umbraco.com/umbraco-heartcore/)
[Content Management sample](https://docs.umbraco.com/umbraco-heartcore/client-libraries/dot-net-core)
[Getting Started](https://docs.umbraco.com/umbraco-heartcore/tutorials/creating-content-with-media)
[Umbraco.Cms.Tests.Integration](https://docs.umbraco.com/umbraco-cms/implementation/integration-testing)
[Github](https://docs.umbraco.com/umbraco-cms/extending/ui-library)
[Readme file](https://docs.umbraco.com/umbraco-cms/extending/ui-library)
[http://localhost:xxxx/da/](https://docs.umbraco.com/umbraco-cms/tutorials/multilanguage-setup)
[version-specific upgrade notes](https://docs.umbraco.com/umbraco-cloud/product-upgrades/manual-upgrades)
[Partial Restore](https://docs.umbraco.com/umbraco-cloud/deployments/restoring-content)
[http://localhost:xxxx/da/](https://docs.umbraco.com/umbraco-cms/v/11.latest/tutorials/multilanguage-setup)
[SurfaceController](https://docs.umbraco.com/umbraco-cms/v/11.latest/reference/language-variation)
[Umbraco Forms](https://docs.umbraco.com/umbraco-cloud/deployments/umbraco-forms-on-cloud)
[auto-upgrades on Umbraco Cloud](https://docs.umbraco.com/umbraco-cloud/deployments/umbraco-forms-on-cloud)
[Contribution documentation](https://docs.umbraco.com/welcome/documentation-and-versions)

**Comment by alina-tincas** [comment]
Hi @Smartmind12 thank you for bringing this to our attention 🙌 

I have resolved the broken links in these commits: [20](https://github.com/umbraco/UmbracoDocs/commit/cf6816c31c55920ce6363bcb4362cbf478ec79a9), [81](https://github.com/umbraco/UmbracoDocs/commit/c910b679bbe9292ac790ee06e01984afd3a837ae), [69](https://github.com/umbraco/UmbracoDocs/commit/25a516c294593ad1e2e012c7e4edbd15a9e50fb0), [32](https://github.com/umbraco/UmbracoDocs/commit/4042a71888b669a7255b546593171e38935bf0cc), [99](https://github.com/umbraco/UmbracoDocs/commit/9ce05b2058f85d59b8ffc4f264d630b2ff5ac306) and [35](https://github.com/umbraco/UmbracoDocs/commit/24917aad4b8a15cbfcb5703489e4d2884a9d8d6e)

However, I was not able to determine where is the broken link as mentioned here [version-specific upgrade notes](https://docs.umbraco.com/umbraco-cloud/product-upgrades/manual-upgrades). Can you please elaborate a little bit more on where is this broken link on the mentioned page in order to fix it? 😊

**Comment by Smartmind12** [comment]
> Hi @Smartmind12 thank you for bringing this to our attention 🙌
> 
> I have resolved the broken links in these commits: [20](https://github.com/umbraco/UmbracoDocs/commit/cf6816c31c55920ce6363bcb4362cbf478ec79a9), [81](https://github.com/umbraco/UmbracoDocs/commit/c910b679bbe9292ac790ee06e01984afd3a837ae), [69](https://github.com/umbraco/UmbracoDocs/commit/25a516c294593ad1e2e012c7e4edbd15a9e50fb0), [32](https://github.com/umbraco/UmbracoDocs/commit/4042a71888b669a7255b546593171e38935bf0cc), [99](https://github.com/umbraco/UmbracoDocs/commit/9ce05b2058f85d59b8ffc4f264d630b2ff5ac306) and [35](https://github.com/umbraco/UmbracoDocs/commit/24917aad4b8a15cbfcb5703489e4d2884a9d8d6e)
> 
> However, I was not able to determine where is the broken link as mentioned here [version-specific upgrade notes](https://docs.umbraco.com/umbraco-cloud/product-upgrades/manual-upgrades). Can you please elaborate a little bit more on where is this broken link on the mentioned page in order to fix it? 😊

Hey @alina-tincas i wanted to work on this issue as a contribution ti hacktoberfest so i would like to raise a PRto close all the above broken links!

**Comment by alina-tincas** [comment]
Hi @Smartmind12 apologies, I was not aware this was your intention so I went ahead and fixed the broken links except this one: [version-specific upgrade notes](https://docs.umbraco.com/umbraco-cloud/product-upgrades/manual-upgrades) 🙈 

You are more than welcome to just create a PR going forward if you notice any broken links instead of opening an issue, **or** you can mention in the opened issue that you will soon create a PR for this 👍

**Comment by Smartmind12** [comment]
> Hi @Smartmind12 apologies, I was not aware this was your intention so I went ahead and fixed the broken links except this one: [version-specific upgrade notes](https://docs.umbraco.com/umbraco-cloud/product-upgrades/manual-upgrades) 🙈 (as mentioned in my last comment)
> 
> You are more than welcome to just create a PR going forward if you notice any broken links instead of opening an issue, **or** you can mention in the opened issue that you will soon create a PR for this so that others do not work on this👍

I too just realiased that i forgot to mention on the issue that i would like to work on it 😅 thanks for working on it and for remaining links i will make a PR at the earliest!

**Comment by Smartmind12** [comment]
I have fixed the version upgrades link

**Comment by alina-tincas** [comment]
Awesome! 🎉 

As the PR is merged in, I am closing this issue 💪
