### ISSUE TITLE
Header links does not forward you to corresponding section

### ISSUE THREAD

**Issue by Frost117** [umbraco/UmbracoDocs#5765]
## What type of issue is it? (Choose one - delete the others)
Other (write it here)
Issue with header links

## What article/section is this about?
(link here)
On the /welcome/ page

## Describe the issue
When you click on CMS or Cloud the link is redirecting you to /welcome/ instead of /umbraco-cms/v/x.latest/.

The only way (without using google) to get into CMS docs is to go to the Heartcore link, and then click on the CMS link where it works.
![image](https://github.com/umbraco/UmbracoDocs/assets/32164310/9d9dcc14-fc82-432c-8137-a5a68fafc8df)

The same issue is with the Cloud link
![image](https://github.com/umbraco/UmbracoDocs/assets/32164310/fe44b68b-8bf2-4d99-93dd-18fe02bb3737)

**Comment by alina-tincas** [comment]
Hi @Frost117 thank you for bringing this to our attention! 
https://docs.umbraco.com/welcome/ should not have a header so I have just removed that. The reason for this is because this page has a summary of all docs that can be found and the way you can find them is to click on them. For example if you want to go to umbraco cms then you click on umbraco cms etc:
![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/8fe23398-b3f6-463c-b383-afe50ce7ed43)

Do you think in this case it would be an idea to add [a hint note ](https://docs.gitbook.com/content-editor/blocks/hint) that all blocks have links attached to them so if you would like to visit a documentation just click on the block?

**Comment by Frost117** [comment]
Sure, that's an idea.

From my experience using this page, it did not struck me that these "Blocks" are actually something you can click. 

Though I prefer to have the Header link available, because that was very clear on what sections are available.

Forexample if I look at the /welcome/ page now, how can I know that the Marketplace is something that I can visit? 
Or that I can change to dark mode

**Comment by alina-tincas** [comment]
I have talked further with the team and to make the block more obvious that they are links that can be interacted with, we have made the name of the product as a link as well (as normally a text in blue is clickable)

![image](https://github.com/umbraco/UmbracoDocs/assets/83591955/366e06f0-3be3-4ad7-9b8f-df91a16a0b90)

There are more option apart from dark mode when clicking on the 3 dots. However for this page we do not expect users to spend much time on as it serves as a summary of the different documentations and link between them. This is the reason why the navigation is not the same as the other documentation pages and that the dark mode is not so visible. 

Let me know what you think of the update of adding links to titles as it currently is on https://docs.umbraco.com/welcome/?

**Comment by alina-tincas** [comment]
Heya @Frost117 as I haven´t heard from you in a while, I am closing this issue. If you have any other suggestions you are most welcome to[ create a PR ](https://docs.umbraco.com/welcome/contribute/pull-request) or open a new issue or get back to this thread and then we can take it from there 😊
