### ISSUE TITLE
Update Article about member registration and login

### ISSUE THREAD

**Issue by JohanReitsma83** [umbraco/UmbracoDocs#5892]
## What type of issue is it? (Choose one - delete the others)
Discussion

## What article/section is this about?
[Member Registration and Login](https://docs.umbraco.com/umbraco-cms/tutorials/members-registration-and-login)

## Describe the issue
Would it be an idea to update the logic for this using next to macro's the block grid editor and blocklist editor? And also add the logic for updating the profile.

For example, there is also an Edit Profile macro but not mentioned.

**Comment by alina-tincas** [comment]
Hi @JohanReitsma83 👋 

With **macros** and **partial view macros** [being removed in v14 ](https://github.com/umbraco/Announcements/issues/14) I believe it makes perfect sense for this article to be updated 👍 

The article can be updated so that it uses Partial view snippets instead of partial view macro files or macros (as the snippets such as **edit profile** is the same when creating partial view with snippets). Or the article can be updated to use blocks in RTE or Block Grid. 

Leaving this as up-for-grabs if anyone would like to contribute with a new example 🙌

**Comment by JohanReitsma83** [comment]
I will pick it up, already working on this with the Blockgrid editor in my project so can do this also.

**Comment by alina-tincas** [comment]
That's awesome 🙌 #h5YR

**Comment by sofietoft** [comment]
Hi @JohanReitsma83 

I noticed that the Member Registration and Login guide has been verified and updated for Umbraco 14.
It no longer uses Macros/Partial View Macros.

With that, I'll close this Issue.
Feel free to get in back in touch, should you have further questions or comments.
Thanks!
