### ISSUE TITLE
Multiple CC or BCC email addresses

### ISSUE THREAD

**Issue by ava3a13** [umbraco/UmbracoDocs#6059]
## What type of issue is it? (Choose one - delete the others)
Missing documentation

## What article/section is this about?
[Workflow Types](https://docs.umbraco.com/umbraco-forms/editor/attaching-workflows/workflow-types)

## Describe the issue
Neither workflow, nor core documentation deals with the question of the multiple CC (and/or BCC) email addresses. And having looked into the `WorkflowEmailService`  it is clear that functionality is present, where `addresses` string passed into in `ParseMailAddresses` is being split by the `;` or `,` characters and further `emailSender` class from the core handles the `string[]` . It took some digging into the forms code to check it out. I am not sure whether the docs should include this as an example, or whether it should be placed under core or forms, or both. Either way I can give a small PR in the workflow types section and you take it from there.

**Comment by alina-tincas** [comment]
Hi @ava3a13 thank you for bringing this to our attention 🙏 

You are more than welcome to create a PR and then we can take it from there 💪 😊

**Comment by sofietoft** [comment]
Hi @ava3a13 👋 

It's been a while since we've heard from you.
I was wondering whether you're still up for adding some docs on how to enable adding multiple CC email addresses when using Umbraco Forms email workflow? 🤞 

Hacktoberfest i coming up, so I'll be putting some more tags on this one, and adding it to the Hacktoberfest 2024 project board for Umbraco.

**Comment by ava3a13** [comment]
@sofietoft yes, I will be giving a pull request
