### ISSUE TITLE
Section in ModelsBuilder docs referes to old nuget package

### ISSUE THREAD

**Issue by gmanrodt** [umbraco/UmbracoDocs#6066]
Wrong documentation

## What article/section is this about?
[(link here)](https://docs.umbraco.com/umbraco-cms/reference/templating/modelsbuilder/install-models-builder)

## Describe the issue
This section of the documentation talks about installing the "full version" of the ModelsBuilder via a nuget package. However, ModelsBuilder is now baked into Umbraco,Infrastructure, and is no longer a separate package. I believe the above page can be wholly removed, along with any references to it. 

I messaged @alina-tincas about this, and she recommended opening this issue. I am a bit busy to delete the page myself, and ensure nothing else was referencing it. :(

**Comment by alina-tincas** [comment]
Hi @gmanrodt thank you for bringing this to our attention 🙏 

And do not worry about not being able to create a PR for this, we already appreciate for letting us know that we have some outdated docs! I will set this up for grabs if anyone would like to pick this up and make a PR for removing this page and additionally checking the other models builder articles to see if there are more of them that are outdated. 👍 

Otherwise, I have also set this in our backlog to pick it up when we can.

**Comment by jonat123** [comment]
@gmanrodt Thanks for creating the issue! :D 

I have created a PR which removes the old articles 😊

Once I merge in the PR this issue will be closed 😄

Thanks for helping out! H5YR!! 😎
