### ISSUE TITLE
Missing an "a"

### ISSUE THREAD

**Issue by umbracowulser** [umbraco/UmbracoDocs#608]
In the section: https://our.umbraco.org/documentation/Tutorials/ the name: "Creating Basic Site" should have and "a" in it so it ends up being named: "Creating a Basic Site".

**Comment by marcemarc** [comment]
Hi @umbracowulser

Ahh, good spot, you mean in the left-hand navigation? 

There is a slight issue with changing it here because it's generated from the name of the folder, and so if we change the folder name, it will cause lots of broken links!

and so we'd have to ask @nul800sebastiaan nicely to create redirects to ensure people can still find this content, if we do add the 'a'...

so whilst it seems like a quick change, that's why we haven't acted upon it quickly!

if that makes sense.

**Comment by umbracowulser** [comment]
Hi @marcemarc ,

Yes exactly. It just caught my eye that the syntax was off in the navigation in comparison to the rest of the links.

But I understand that it's not such a simple fix as I assumed, so it makes sense that it is not a top priority to change it. After all it is only a minor thing, I am certain people can find their way around in the navigation as it is now.

Thank you for getting back to me an clarifying.

Best regards - Martin
