### ISSUE TITLE
Sensitive data for Members Properties Incorrect

### ISSUE THREAD

**Issue by nobledm** [umbraco/UmbracoDocs#6089]
## What type of issue is it?
Wrong documentation

## What article/section is this about?
[Sensitive data: Marking data as sensitive](https://docs.umbraco.com/umbraco-cms/reference/security/sensitive-data-on-members#marking-data-as-sensitive)

## Describe the issue
v13 instance does not appear to have any 'Is sensitive data' property for member data. This whole section is an invalid tutorial. Or... is a bug in CMS I should report instead? ^^;

![image](https://github.com/umbraco/UmbracoDocs/assets/40868595/9e0a22c4-86f2-438c-8509-292dfd209d84)
*viewing as an Administrator so nothing should be hidden

**Comment by jonat123** [comment]
@nobledm Thanks for creating this issue 😊

To be able to mark a property as sensitive on a member, your user needs to be part of the "**sensitive data**" group.

Otherwise, you won't be able to mark the property, even though you are an administrator.

This is also explained in this part of the [documentation](https://docs.umbraco.com/umbraco-cms/reference/security/sensitive-data-on-members#grant-or-deny-access-to-sensitive-data).

I hope this makes sense 😊

This also means that the tutorial is correct.


I will go ahead and close this issue. 

I hope you have a great day 😄
