### ISSUE TITLE
Missing documentation about using umb-property component in reference

### ISSUE THREAD

**Issue by BishalTimalsina12** [umbraco/UmbracoDocs#6146]
Missing documentation in v14

## What article/section is this about?
[](https://docs.umbraco.com/umbraco-cms/reference/dive-into-the-code
)## Describe the issue

i think there should be a detailed information on how we can use umb properties when extending umbraco. as for me im working on package which uses umbraco properties in the fields, so when sending the form to the server , the content is sending null. not soo much resources out there that has been helpful

**Comment by jonat123** [comment]
Hello @BishalTimalsina12 😄

Thanks for creating this issue!

I am unsure what it is you mean when you say you want more detailed information on how we can use umb properties when extending Umbraco.

Can I get you to expand on what information you are missing in our documentation? 😊

That would be a great help! 😄

Best regards
Jonathan

**Comment by sofietoft** [comment]
Hi @BishalTimalsina12 👋 

It's been a while since you reported this, and we have been making a lot of changes to the documentation for Umbraco 14 since then.
That in combination with it's been a while since we've heard from you, I'll be closing down this issue for now.

Please do not hesitate to reopen or get back in touch, if you still feel some information is missing from our documentation 💪 

Thanks again for helping us keeping the docs up to speed!
