### ISSUE TITLE
Add a better explanation how to configure sinks

### ISSUE THREAD

**Issue by bryansan-msft** [umbraco/UmbracoDocs#6161]
## What type of issue is it? (Choose one - delete the others)
Incomplete documentation

## What article/section is this about?
Umbraco CMS: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/logging
Application insights Serilog sink: https://github.com/serilog-contrib/serilog-sinks-applicationinsights?tab=readme-ov-file

## Describe the issue
The Umbraco CMS documentation is relaying on the serilog sink documentation to explain how the configuration is done. In the case of application insights, the serilog sink documentation is poorly written as it doesn't show how to do it for the latest Application insights SDK and Asp.Net version.

I have been two days reverse engineering Umbraco CMS and this serilog sink to try to configure application insights when it should be a straightforward process.

Can we have an example of how to do so in the main Umbraco CMS documentation at least for one sink? or at least can you provide me one example and allow me to make a PR to improve Umbraco CMS documentation?

**Comment by eshanrnh** [comment]
Hi @bryansan-msft,

Thank you for bringing this to our attention. It sounds like there are gaps in the current documentation and we understand how frustrating it can be.

We will look into improving the documentation by either adding an example or reaching out to the developers responsible for this area.

In the meantime, if you have any specific insights or find a working example from your efforts, we would love to see a Pull Request (PR) from you. Your firsthand experience could greatly benefit other users facing similar challenges.

We will keep you updated on our progress.

**Comment by sofietoft** [comment]
Hi @bryansan-msft 

I've chatted with our developers about the information you feel is missing from our documentation platform.
We will not add an example or guide on implementing this, to our documentation.
Why? Because it will leave us with a maintenance issue since we will need to update the example whenever the Application Insights Serilog documentation updates.

Our developers also provide me with a link to how we are implementing a console sink in our own codebase: https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI/appsettings.Development.template.json#L3-L25 
Finally, when our developers need to built something similar, this is the documentation they use: https://github.com/serilog/serilog-settings-configuration

I hope this all makes sense, and that you can use the resources mentioned.
I'll close this issue for now, but please feel free to get back in touch should you have further questions or comments.

Thanks for helping us making the Umbraco Documentation the best it can be! 😄
