### ISSUE TITLE
Hard to find version specific docs

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/UmbracoDocs#6237]
Following the launch of Umbraco 14 it has become almost impossible to find docs for previous versions (e.g. v13).

This has always been the case when a new major version launched, but mattered less as v9-v13 docs were largely the same...

Previously I would perform a Google search to find Umbraco documentation. Now, even searching for something and including "umbraco 13" does not return the correct results.

Now a search for "umbraco package manifest" takes you to [this page](https://docs.umbraco.com/umbraco-cms/extending/package-manifest) with no clear way to get to the pre-v14 version of the docs. Using the version switcher in the header you are simply taken to the root page of the docs for that version – not to the equivalent page in the docs as I would hope.

Another major issue here is that the URLs for the current major version of the docs do not include a version number. When v14 launched this means docs previously at /* are moved to /v/13.latest-lts/* and the new docs are placed at /*. There are no redirects in place to take you to the old docs. This will continue to happen for each major version going forward. Using the same package manifest example above, the first result in Google is [this link](https://docs.umbraco.com/umbraco-cms/extending/property-editors/package-manifest) which now leads to a 404.

**Suggestion:** we should always include the version number in the URLs. This way search engines will index the right version specific content, and URLs won't change with the new version.

**Comment by sofietoft** [comment]
Hi @callumbwhyte !

Thanks for sharing your thoughts on this.
I realize that the fact that Umbraco 14 is so much different from Umbraco 13 does introduce a bit of struggle in terms of finding the correct documentation.

I'm not sure whether we can add the version number to the URL for the "current version", or if that's even the best solution here, but I'll definitely look into it!

I've recommended other people to **bookmark a link to the version of the docs they need most often**, and then use the search option from there to find what you need. So, bookmark [the Umbraco CMS landing page for version 13](https://docs.umbraco.com/umbraco-cms/v/13.latest-lts) and go from there.

Regarding the Package Manifest file specifically - the reason you cannot find that via Google at the moment, is because we've recently moved it to a new location with the 14 docs. The redirect worked a few days ago, so not really sure what happened, but I'll make sure this is resolved asap! 💪

**Comment by callumbwhyte** [comment]
Thanks @sofietoft,

RE URLs – we discussed on the package team this morning that perhaps the "current version" URLs (/*) could just have redirects to their equivalent versioned page. If this is a temporary 302 redirect it shouldn't be a problem to change them in future. The redirects could either be to the "latest" version or to the LTS version (perhaps more desirable!)

RE bookmarking – this is a workaround, but the in-docs search is not quite good enough to make this viable. Equally for deeply nested pages the side navigation makes this hard to find. I feel many other would use Google to find docs as a more natural option.

Cheers!

**Comment by sofietoft** [comment]
If I remember correctly, changing the version of the article you're viewing used to work - so, when changing versions on the docs site, you would be shown the same article but just for that new version. 
I've raised this with GitBook and I'll follow up after summer.

Google search should be a valid source of information, and I realize this is not currently the case unless you've already started using 14 for everything - which naturally isn't the case for most!!
I'll need to figure out how best we can approach this, given the options we have with the platform 💪 

This is also being discussed on Discord, if you want to share your thoughts there: https://discord.com/channels/869656431308189746/1255806029283721238

**Comment by bjarnef** [comment]
Is is also possible to simplify URL segment for version independent of dropdown value?

So instead of:
https://docs.umbraco.com/umbraco-cms/v/13.latest-lts/reference/notifications/cacherefresher-notifications

Then just:

https://docs.umbraco.com/umbraco-cms/v/13/reference/notifications/cacherefresher-notifications

or 
https://docs.umbraco.com/umbraco-cms/v13/reference/notifications/cacherefresher-notifications

**Comment by sofietoft** [comment]
Hi all 👋 

I appreciate all the input you've given us here regarding the searchability concerning the release of docs for a new major version.

As you might have noticed, changing the version of the docs using the version dropdown does not send you to the root of the site for that version anymore. Instead, you are shown the article equivalent to the one you were viewing on the previous version.
So, that now works as expected 💪 

Regarding the URLs and the redirects, I'm afraid there isn't much to be done at this time.
The "current" (default) version of the docs for a given product, will always have a "clean" URL, meaning the version number will not be a part of it. This is how the GitBook platform operates, and we cannot override it at this time.
We do not currently have the option to create redirects between the versions, as we are using separate spaces for each version.

As for removing the ".latest-lts" from the URLs for the not-current versions, this is not something we will be changing. The decision to add this information was made to ensure readers that they are viewing the latest docs for their version. It also gives us the option to highlight the LTS versions.

With that said, GitBook has been releasing a lot of new features lately, and I have yet to catch up with all of it!
We of course want to utilize all the best features of the platform, to give you the best possible experience when coming to the Umbraco Docs 🙌 

Thanks for providing feedback! It is always much appreciated.

I will close this issue for now.
Please do not hesitate to get back in touch, if you still have comments and or questions related to this.
