### ISSUE TITLE
Difficult to search "old" documentation

### ISSUE THREAD

**Issue by bjarnef** [umbraco/UmbracoDocs#6289]
## What type of issue is it? (Choose one - delete the others)
Discussion
Missing documentation

## What article/section is this about?
General docs

## Describe the issue
After documentation has been updated to show latest v14, I find it difficult to search old (v10-v13) docs as been incoming links from Google redirects, e.g. search for "umbraco content apps" on Google.

![image](https://github.com/user-attachments/assets/e88e426a-e8e0-41dd-b31c-d9f75ee3b0a4)

Clicking "Content Apps | 13.latest (LTS) | Umbraco CMS" then redirects to https://docs.umbraco.com/umbraco-cms/extending/workspaces/workspace-editor-views which is v14 documentation.

Switching to v13 directs to https://docs.umbraco.com/umbraco-cms/v/13.latest-lts

![image](https://github.com/user-attachments/assets/bc519622-3c8b-48a9-b7de-393b949be020)

Searching for "content apps" here returns no results.

https://docs.umbraco.com/umbraco-cms/v/13.latest-lts?q=content+apps

But there are plenty of info available about content apps here: https://docs.umbraco.com/umbraco-cms/v/13.latest-lts/extending/content-apps

I thins this can be improved as the "old" documentation is still very much relevant and all concepts from v13 is not directly available in v14 and some stuff has changed or been moved.

**Comment by eshanrnh** [comment]
Thank you, @bjarnef  for bringing this to our attention 🙌

I followed the steps mentioned above but I am unable to replicate the issue 🤔 We cannot control the links displayed by Google in its search results and they should definitely not redirect to a different article (Workspace Editor Views) 😳

Could you try clearing your browser's cache to see if the issue still occurs?

https://github.com/user-attachments/assets/771c7758-f5df-4298-8bc1-4e613461449d

**Comment by bjarnef** [comment]
Hi @eshanrnh 

Yes, it may only be some links with equvalent page in v14, which is redirected.

When I tested I seached in docs at top level in v13 docs.

In the video you are on a deeper level.

**Comment by eshanrnh** [comment]
Ah, okay.. 😀 I tried the search functionality at the top level and that works fine too. 

I'll leave this issue open for now and ask someone else from the team to test it out once they are back from vacation ☀️

**Comment by sofietoft** [comment]
Hi @bjarnef !

Are you still experiencing issues with this?
I've run some tests this afternoon, and am unable to reproduce what you're reporting.

Searching for "Umbraco Content Apps 13" on Google gives me a few options.
![image](https://github.com/user-attachments/assets/885420d6-b754-46da-a2fc-c33390a07879)
This link sends me to the correct article in the docs: https://docs.umbraco.com/umbraco-cms/v/13.latest-lts/extending/content-apps

Searching on the docs platform, you can switch to "All content" instead of only the current version.
This enables you to find docs for other versions than the one you're currently viewing.
![image](https://github.com/user-attachments/assets/4a970de2-db8c-48d9-b5d8-704ff7e0e994)

Please give it another go, and let me know what you experience.
Hopefully it'll be the same!
But, as Esha mentioned, a hard refresh of the cache might be necessary! GitBook uses some heavy caching for some reason!

**Comment by bjarnef** [comment]
@sofietoft yes, it seems to work now, must be caching or something.

Let's close this as much of searching the version specific docs is what @callumbwhyte reported here: https://github.com/umbraco/UmbracoDocs/issues/6237
