### ISSUE TITLE
Add date stamp to all docs

### ISSUE THREAD

**Issue by benbracedigital** [umbraco/UmbracoDocs#630]
Could we a date stamp to all documents? There are a few instances where pages change such as https://our.umbraco.org/documentation/getting-started/setup/server-setup/azure-web-apps changes with different Umbraco versions so it'd be good to see when pages have been updated

**Comment by OwainWilliams** [comment]
I liked this idea so decided to look in to implementing it. Not a easy as I first though. 
Due to the way the documentation is imported in to the CMS, via a zip file which is downloaded from Git, there isn't any meaningful timestamp available. All the files in the zip file have the same created date - the date the zip is saved. 

I then looked at a way to add a timestamp to each page within Git prior to it being downloaded, again, not possible. The only way I can see to do this is manually. Which isn't great. 

I'll keep on thinking of ideas though. 😄

**Comment by liamlaverty** [comment]
Might be able to get this info with the github api:

https://stackoverflow.com/a/25921837/1663868

`GET /repos/:owner/:repo/commits` with a `path` should give you the committer dates per directory (maybe per file, I've not been able to test it).

**Comment by ed-parry** [comment]
Might be worth closing this issue as there's a separate one for the same item on the Our repo [here](https://github.com/umbraco/OurUmbraco/issues/245), which is where the change would need to be implemented. Been an eerily similar discussion there in the past couple of weeks too!

**Comment by jmayntzhusen** [comment]
I will close this issue now since there is a pending pull request for adding YAML to handle version specific documentation here: https://github.com/umbraco/OurUmbraco/pull/308 

I believe that will fix the issue described here - I can share a sneakpeak of how it will look:
<img width="434" alt="udklip" src="https://user-images.githubusercontent.com/36075913/45675548-e84cbb80-bb2f-11e8-934a-99046165f1c7.PNG">
