### ISSUE TITLE
Reorganize "Getting Started" pages

### ISSUE THREAD

**Issue by alindgren** [umbraco/UmbracoDocs#657]
I find many of the pages in the "Getting Started" section not really about things I would consider for getting started.  For instance, "load balanced setup" and "Subscribing to events" are in the "Getting Started" section but to me seem like more advanced topics. Before reorganizing things in a way that makes sense to me (and making a PR), I'd like to hear what other people think.

**Comment by marcemarc** [comment]
Thanks alindgren! I agree, I think partially it's an issue with the term 'getting started' and sign-posting -
 for me this is a section which 'gets you started' nothing more - but from what starting point? Installing on a server, running locally in visual studio - or you have a cloud install, and your staring already at the backoffice?

I think currently we're aiming 'getting started' to cover everything, all the possible options of getting started but that can then be too much information and be confusing for people who are getting started...

So I think there needs to be an introduction to 'getting started' that then establishes where you are in your Umbraco journey and sign posts you to the appropriate 'section landing page' for the point at which you want to start from.

Since the current Getting Started section deals with installing on a server, it's then become the only place in the docs where server info, hence the advanced topics have crept in, alongside the getting started topics, and provide noise around the topics that will genuinely get you started.

The backoffice overview is a good example of a page, that appears focussed on 'getting started' https://our.umbraco.org/documentation/Getting-Started/Backoffice/ and is really great at introducing the backoffice, but then peters into a glossary of back office terms. (there probably should be a glossary of backoffice terms!) but it might be better here to 'break out' to pages which explain further the concepts of Umbraco, and getting started under headings which introduce the topics first and not the terminology - eg instead of heading on 'Members', the heading is 'Interacting with visitors to the site' etc  

There's a lot to consider, and changing the structure of the pages will introduce broken links, so agree needs a bit of thought, and that bit of thought will improve the 'getting started' journey for people, and other journeys too (eg who looks in getting started for load balancing info?)

Think we need to analyse search terms too, and try some card sorting exercises, to understand where things best live, and what we call particular groupings of documentation...

Anyway you asked what people think, that is what I think... be interested to see/hear what you and others think about the structure of docs, (sketches on a back of an envelope accepted) and how people engage with docs, from the getting started perspective, and also common journeys to dip in to look something up...

**Comment by jmayntzhusen** [comment]
I have also found the 'Getting started' section way too comprehensive for me (I just started learning Umbraco about a month ago), my suggestion would be to split it up a bit more.

If we stole an idea from the way Angular does it: https://angular.io/guide/quickstart
They have a section called 'Quickstart' that basically helps you set up a new site for a complete beginner, as well as do a quick overview of their folder structure and what you can find in them.
Then they have a few basic tutorials in their 'Tutorial' section that helps new users to try some of the commonly used functionality.
Finally they have a section called 'Fundamentals' that, as @marcemarc mentions, covers all the different options of 'Getting started' regardless of what you want to get started with.

Maybe a solution could be to split the install part and the backoffice overview into a new menu point similar to 'Quickstart' and then have the rest of the documentation remain where it is.

**Comment by OwainWilliams** [comment]
I agree with everything above. I found when I was just getting in to Umbraco the getting started section was also too high level. It presumed you knew what you were doing in many cases. I know it's always a good idea to do training e.g. Umbraco.TV or the official training days to get more knowledge but this section really needs to be written in step by step guide form. Make it as easy as possible for people to get an Umbraco site running quickly. Then guide them through creating pages etc. I guess the new 'tour' facility in the backoffice will help with this as well.

**Comment by NikRimington** [comment]
I think getting started, as others have said, is a very broad topic. What might be helpful could be sections such as

- Getting started locally (or quickstart) which focuses on your local environment, VS etc
- Get started with cloud (quick intro to cloud linking through to the main cloud docs)
- Knowing Umbraco (talking about back office, structure, etc)

Then you could move more onto sections that target specific rolls:

 - Getting started as an editor
 - Getting started as a developer
 - Getting started as a user manager

All of these could be simple pages that discuss the pure basics of things you might need to know, such as user roles, sorting, publishing, creating pages etc.

I guess that raises other question, who is the Getting Started aimed at, and who are these docs aimed at? Is it primarily at Devs (I would have thought so based on content)? Lets include Editors and help them on core editor related functionality?

**Comment by liamlaverty** [comment]
I think the WordPress (don't hate me pls) [Where To Start pages](https://codex.wordpress.org/New_To_WordPress_-_Where_to_Start) are a really good place to look for inspiration. It's fairly concise, but pretty much links out to everything you'd ever need to know to get from nothing to a deployed website inside of one document.

It also guides you through checking if you're in the right place. It's a technical document, but the first section makes you go away and look at what Blogging is, what WordPress is etc.

They also have their [5 minute installation guide](https://codex.wordpress.org/Installing_WordPress#Famous_5-Minute_Installation) for people who are comfortable working in php already, or for people who already know WordPress but haven't installed anything recently.

**Comment by marcemarc** [comment]
Thanks all, keep observations coming!, reading and digesting - and we're discussing in the documentation curators team - we're still in our primary phase (that makes it sound rather grand, getting existing PRs processed, we're down to one page of PRs instead of four! - and now trying to reduce open issues of missing documentation - eg lets make obviously missing docs exist, even if it's in the wrong place) - so don't feel like these observations aren't being immediately being acted upon, it's all really good stuff, and will be the first port of call when the admin of the repo is more manageable! - There will also almost definitely be some sort of open space around this 'getting started journey' and the docs generally at CodeGarden if you are attending, if not then, this is the best place to bring peoples thoughts and ideas together!

**Comment by FransdeJong** [comment]
The getting started should be coupled to the new Starterkit (umbraco demo) in the future. A starting developer can than open the starter kit and see a example of what he is reading in the documentation.

**Comment by ravimotha** [comment]
I think there are a couple of ideas we should be stealing/borrowing bodging together.. :

1. Quickstart Guide: how to get up and running in x minutes  
2. Quickstart Guide: getting up and running in the Cloud
3. Find out how to 

- Get started as an editor
- Get started as a developer
- Get started as a user manager
4. Advanced Documentation: 

- load balanced Solution 
- Api Documentation
- Using AWS
- Using Azure
- Using Umbraco Cloud

etc

 //idea from @liamlaverty and @NikRimington

**Comment by jmayntzhusen** [comment]
I will close this issue for now. We all agree that some reorganization of the docs are a great idea, but we are not quite at the point where it makes sense to do so yet.

We are working on improving our tooling to improve the flexibility of the docs structure, once that has been implemented we can reopen a discussion of what we should do.
