### ISSUE TITLE
Reorganize the page about umbracoSettings.config (or improve the search)

### ISSUE THREAD

**Issue by abjerner** [umbraco/UmbracoDocs#659]
Just creating an issue here, as the documentation search has some room for improvement, or the page about `umbracoSettings.config` should be reorganized.

Let's try the following:

1. Search for *scheduled tasks*
2. Look for a matching result in the list
3. Where to look?

![image](https://user-images.githubusercontent.com/3634580/36452251-17a78e6e-1694-11e8-9441-b7f09ec8bfa6.png)

The problem here is that the title and the summary of the page mentions nothing about scheduled tasks, so a user is probably not that like to click this result.

Perhaps the search should show a short text with the part of the page contents that matches the search words.

Another solution could be to move the part about scheduled tasks to it's own sub page (and probably the same for the other sections). Then it would be easier to find the page in the search results.

**Comment by marcemarc** [comment]
Yes,, been trying to get my head around the best way to document configuration, and it's the issue you mention that is exactly the thing!, topics kind of need 'introducing' and 'describing' with text that makes them findable... regardless of where they are configured - but also 'quick lookup' of configuration is a more frequent activity, and seeing the config in the context of the description, can be more effective in communicating how something works. 

UmbracoSettings is the worse culprit because so many different things are configured there!

I think search has a part to play in understanding the terms people are searching for, (I'm sure half of peoples opinion on the docs is influenced by findability) and therefore how the documentation should be structured to lead people through to find what they need, but think your suggestion of showing an extract from the matching search result would be a good 'quick win sticking plaster' over the ad hoc organic nature of the current documentation as we work towards a better pattern of structuring information vs configuration.

**Comment by abjerner** [comment]
I like the idea of splitting the page into multiple sub pages, and the current page for **umbracoSettings** could have some basic information, but otherwise just be a index list of the sub pages. That would also create a better context for more details and possibly also examples.

Regarding the search, perhaps we could take some inspiration from GitHub's search:

![image](https://user-images.githubusercontent.com/3634580/36525687-5afa7a74-17ab-11e8-843a-594055edf49e.png)

**Comment by jmayntzhusen** [comment]
I see the appeal of indexing this better by splitting it up. 

I am really not a fan of having many sub pages, especially since we can't show them properly in the menu as it only covers the top three levels. 
I don't know if you have had a look at the [migrating to Cloud guide](https://our.umbraco.com/documentation/Umbraco-Cloud/Getting-Started/Migrate-Existing-Site/) but I can tell you that a lot of users never make it to page 2.

Don't know if the solution is to always make a "menu page" with sub pages as we would end up many levels down.

**Comment by sofietoft** [comment]
Hi! 
As we haven't seen any new activity on this issue in while, I'll close it for now.

If you feel it's still relevant, you're welcome to reopen it! 😁 
Thanks.

/Sofie
