### ISSUE TITLE
Umbraco Backoffice UI API Documentation needs examples

### ISSUE THREAD

**Issue by drpeck** [umbraco/UmbracoDocs#664]
The Umbraco Backoffice UI API Documentation has a lot of information, but with no demos or images of what an element refers to it is of limited use.

An example; I was shown a property editor that uses umbMediaGrid today. I was told that umbMediaGrid is all properly documented, and it is:
https://our.umbraco.org/apidocs/ui/#/api/umbraco.directives.directive:umbMediaGrid

Unfortunately I can't think that anyone would know what umbMediaGrid actually is without first reverse engineering something else.

**Comment by marcemarc** [comment]
Agree, we've talked in the past about having a visual 'style guide' to the directives, so you could thumb through screenshots of the interaction that you are used to seeing in Umbraco and then be able to find the name of the directive that creates that type of interaction! as you say, nobody will search for 'slidey out panel thing' and get umbOverlay etc

**Comment by Jeavon** [comment]
There is some great content in the Umbrangular slide deck that could potentially be re-purposed https://docs.google.com/presentation/d/1ZUt6EPkqZurF4I2IRtKNZSX7Z-6j8eSxr0dzz9dLNgY/edit#slide=id.g2255284922_0_120

**Comment by dampee** [comment]
The umbracolar code is on github: https://github.com/umbraco/umbrangular/
as are the slides (in PDF form): https://github.com/umbraco/umbrangular/blob/master/UmbrAngular.pdf

**Comment by markadrake** [comment]
Sorry to report this but the links shared now result in 404's or access denied.

I agree with @drpeck and @marcemarc's sentiments above. 

**In my opinion the [Umbraco Backoffice UI API Documentation](https://our.umbraco.com/apidocs/v8/ui/#/api/) website needs a facelift for 2020.** 

Umbraco HQ has developed a good amount of frontend elements (or components) based on Bootstrap and Angular. My biggest criticism of the documentation is the lack of visuals (screenshots, captures) to accompany the "directives, filters, and services". There's no visual reference to help hold it all together. What are all these things: boxes, containers, drawers,panes, panels, etc? 

Help new developers acclimate to the design language. 

For experienced developers, this serves as a reference. 

**That Umbraco.Web.UI.Client project could use some attention too.** To start, the documentation for it seems out of date for v8. The documentation skips the root folders, discussing how the project is setup, what the gulp tasks do, which files are editable and which files are built from gulp? [Also this page repeats itself](https://our.umbraco.com/documentation/development-guidelines/umbraco-web_ui-client), and it's hard for me to tell if it's an exact repeat, or if there are subtle changes somewhere.

Just today, when looking around to get a reference to what version of Bootstrap and other various dependencies exist in the project - I discovered multiple files and versions for some of these files. Now I'm wondering - which version of Bootstrap is being used? Is it 2.3.1 or 3.0.1? What about Bootstrap Responsive? Is it 2.1.1 or 2.3.1?

I wanted to pull down the project and run it, get more of an idea of what's happening in the UI project before I said this - but at first glance it looks like some of the commits being made are introducing changes to files that are part of a versioned, 3rd party dependency. I can't begin to describe the anxiety I'd feel if that was true and this was my personal project.

**Comment by sofietoft** [comment]
@markadrake Thanks for the extensive report and your thoughts on the current state of the Umbraco Backoffice UI API documentation. It's much appreciated 😁 

We are aware, that it currently _only_ serves as a reference place for developers who are already familiar with Umbraco and the setup.

There has before been discussions on how we should handle these docs in order to add more examples etc. As these API Docs are currently auto-generated, we haven't yet found a smart way to add in more examples, screenshots, etc.
We are, however, looking into a new platform for the Docs on Our - DocFX, which is also what the API docs currently uses. This platform will allow to add more examples and extend the Backoffice UI Docs as well 💪 

This platform change is something we're looking into for 2020!

For now, perhaps have a look at this other issue: #2045 
More examples to the Backoffice UI API docs has been requested before, and we've come up with a solution that could add more examples - however not directly to the API Docs, but to the Documentation on Our 🤔 Not the perfect solution, but an option non the less!

You're more than happy to join the conversation there, and tell me what you think! 😁

**Comment by sofietoft** [comment]
Hi all! As I don't think it makes sense to have 2 issues open around the same topic, I'm closing this one for now.

Please refer to #2045 for more details on the topic of Backoffice UI API Documentation 💪
