### ISSUE TITLE
Umbraco Forms Documentation Outdated for Developers

### ISSUE THREAD

**Issue by idseefeld** [umbraco/UmbracoDocs#916]
https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Rendering-Scripts/

The description is not clear and seems to be outdated anyways, as no _FormsRenderScripts_ macro exists.

**Comment by greystate** [comment]
I agree - It's very confusing at the moment, but that's mostly because the sidebar navigation doesn't show all levels. There *is* actually a page with updated information, but that's hidden in the **Themes** section of the **Developer** docs: 
https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Themes/

And a heading partway down the page reveals the scripting files info: https://our.umbraco.com/documentation/Add-ons/UmbracoForms/Developer/Themes/#rendering-script-content-separately

**Comment by greystate** [comment]
I just somehow duped this (here: #948 ) without at all remembering this one... LOL

Anyway - hope to submit a PR soon that fixes it.
